### ISSUE TITLE
iPhoneをUSBで接続しても切断される

### ISSUE THREAD

**Issue by nalamurapepperlinux** [FascodeNet/alterlinux#100]
症状
iPhoneをUSBで接続したところ、1度は認識されて給電が開始されるものの、およそ2秒後には給電が停止され、認識されなくなる。

（なお、デュアルブートされているPepperMint10では認識されていることから、OS側の問題と思われる）

動作環境
ideapad s12
PepperMint 10とデュアルブート
CPU　intel Atom N270
RAM 1.43GB
ROM 全体・160GB、AlterLinuxのパーミッション・53GB

使用ISO
https://xn--d-8o2b.com/storage/alter/beta/beta3.1/2020.05.26/alterlinux-lxde-2020.05.26-i686.iso

**Comment by Hayao0819** [comment]
ターミナルから`yay -S gvfs-afc`コマンドを実行してシステムを再起動してみて下さい

**Comment by nalamurapepperlinux** [comment]
認識しました。

**Comment by Hayao0819** [comment]
よかったです。AlterLinuxでデフォルトで認識するようにしておきます。
