### ISSUE TITLE
ログイン画面から抜け出せなくなってしまった

### ISSUE THREAD

**Issue by KowerKoint** [FascodeNet/alterlinux#102]
使い方も知らない状態でAlterLinuxにi3-wmを導入しようとした(この時点で軽率だった)んですが、何かが悪いのかログインできなくなってしまいました…

`sudo pacman -S i3 dmenu` でインストールしたあと、~/.xinitrcに`exec i3`を追記して`sudo startx`を実行しましたが、やりながら覚えようなどと適当に考えてたのにブラウザも立ち上がらなくて(下のドックのChromiumをクリックしてもウィンドウが出てこないのは仕様？)どうしようも無かったので適当に`reboot`しました
するとログイン画面が出てきましたが、正しいパスワードを入れても 
```
Loading Linux Linux-zen ...
Loading initial ramdisk ...
```
 の後ログイン画面に戻ってきて入れなくなってしまいました(左下のセッションではXfceとi3が選べるようになっていて、どちらでも同様でした)

これはAlterLinuxの問題とは限りませんが確認よろしくお願いします

**Comment by KowerKoint** [comment]
環境について書き忘れていました

CPU:Intel Core i7-7700HQ
GPU:NVIDIA GeForce MX150
SSD(Windows10とAlterLinux beta2がデュアルブート状態)
HDD

**Comment by KowerKoint** [comment]
追記
Ctrl+Alt+F2で仮想端末にログインして`startx`を実行すると入れました
また、
```
Loading Linux Linux-zen ...
Loading initial ramdisk ...
```
が2連続で出たり途中で止まったりするのは以前Lubuntu 20.04LTSをUSBメモリにインストールhして起動したときからたまに発生していて、メインの問題はそちらだったと考えられます

今回新たにi3を追加したことによりこれまで出していなかったログイン画面が表示され、この問題が表に現れ始めたと考えられます

**Comment by Hayao0819** [comment]
とりあえずi3などを削除してみてください
ログイン画面で Ctrl + Alt + F2を押せばターミナルが起動します

**Comment by KowerKoint** [comment]
i3を削除して再起動しても同様にログイン画面はループし、Ctrl+Alt+F2からstartxすることで入ることは出来ました
このときi3を消す前はXfceの自分が設定したデスクトップが起動していましたが今度はリセットされたデスクトップで、Chromiumなど多くのアプリがクリックしても立ち上がらない状態(上で、i3を入れてstartxした直後の状態)になりました

**Comment by Hayao0819** [comment]
すみませんそこまでになるとやはりわからないです
