### ISSUE TITLE
build-wizard.pyでビルドが開始されない

### ISSUE THREAD

**Issue by Hayao0819** [FascodeNet/alterlinux#103]
```bash
python build-wizard.py
```
で実行後、デフォルト設定のままビルドを開始すると以下のようなエラーがターミナルの``STDERR
に出力されてフリーズする。

![image](https://user-images.githubusercontent.com/32128205/85000585-949c5580-b18d-11ea-9b7c-9244e3036b2a.png)

**Comment by yangniao23** [comment]
ソースを見てもらえばわかりますが未実装です...

近いうちに実装します

**Comment by mk-linux419** [comment]
https://github.com/FascodeNet/alterlinux/pull/193 で再実装されました

**Comment by Hayao0819** [comment]
旧来の`build-wizard.py`は削除してしました。
