### ISSUE TITLE
インストーラーが落ちる

### ISSUE THREAD

**Issue by HimHim1113** [FascodeNet/alterlinux#104]
コンピューターに直接インストールを試みようとインストーラーを起動しました。
最初のメニュー選択(UEFI shellなどが選択肢にある)までは進めるのですが、その後にインストールを始めようと1番上の項目を選択した後に少しだけメッセージが出た後にすぐ落ちてしまいます。
![KIMG2659](https://user-images.githubusercontent.com/43987522/85213932-c8e76000-b39f-11ea-886b-8b5190d9b77e.JPG)

実施環境
Dell Inspiron 15-3552
Celeron N3060
RAM 4GB
ROM SSD 120GB (2つのOSがインストール済み)

**Comment by Hayao0819** [comment]
[このあたり](https://wiki.archlinux.jp/index.php/Dell_Inspiron_11_3000_(3162))を参考にしてみて下さい。おそらくハードウェア依存の問題です

**Comment by HimHim1113** [comment]
他の方は動作するのでハードが問題かと思っていました。
実際その通りなのですね。
ありがとうございました。
