### ISSUE TITLE
Wineをパッケージリストに入れると起動できなくなる

### ISSUE THREAD

**Issue by YYTU-Aqua** [FascodeNet/alterlinux#105]
AlterIsoのpackages.x86_64にwineを追加するとLiveCDは正常に起動しますがインストールし再起動してGRUBの後黒い画面で停止します

**Comment by Hayao0819** [comment]
Grubの項目を編集し、Plymouthを無効化した状態で起動し、ログを確認して下さい

**Comment by Hayao0819** [comment]
また、Wineの具体的なパッケージ名を教えて下さい

**Comment by YYTU-Aqua** [comment]
Plymothは元から無効になっています
ログの確認方法がわかりません
wine-5.11-1です

**Comment by Hayao0819** [comment]
普通に画面に表示されると思うのですが...
パッケージ名は`wine`ですか？それとも`wine-staging`ですか？

**Comment by Hayao0819** [comment]
先程他のチャンネルでwineを追加してみましたが正常に起動し、インストールも完了しました
おそらく起動しないのは他の部分に原因があると思われます

**Comment by YYTU-Aqua** [comment]
ありがとうございます
チャンネルの仕組みが悪かったと思います
wineを外すと起動しました

**Comment by Hayao0819** [comment]
うーん...ソースコードを見ないとなんともいえないです

**Comment by kokkiemouse** [comment]
AURのものはどうでしょうか...
