### ISSUE TITLE
mkalteriso bug

### ISSUE THREAD

**Issue by lap1sid** [FascodeNet/alterlinux#106]
`-w`を使用してビルドすると、alterのpacmanミラーリストが見当たらなくてエラーが発生する

**Comment by Hayao0819** [comment]
実行したコマンドとエラーの詳細を教えて下さい

**Comment by lap1sid** [comment]
`sudo ./build.sh -b -u alter -p alter -w /ram plasma`
日本訳: alter-mirrorlist: そのようなファイルやディレクトリはありません

**Comment by Hayao0819** [comment]
こちらの環境では再現できませんでした...
どのタイミングで発生しているかなどの詳細はわかりますか

**Comment by lap1sid** [comment]
パッケージの準備が終わったあたりですね

**Comment by lap1sid** [comment]
`sudo ./build.sh -b -p 'alter' -u 'alter' -w /ram plasma` で再び試したところ、確実にビルドは出来ましたが workディレクトリに `/ram` を使用してないようです

**Comment by lap1sid** [comment]
どうやら、`-w`で指定したディレクトリが`out_dir`になってるようです
