### ISSUE TITLE
firefoxが日本語じゃない問題

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#107]
Twitterにて下記ののようなつぶやきがあり開発グループに確認したところ日本語パッケージの導入し忘れらしいのでissueを立てます。

言われてみればalterlinuxのデフォルトのfirefox 、英語のままだった、、
まあ、「firefox Japanese」で検索して拡張機能入れればいいんだけど、、
https://twitter.com/nakamurapepper/status/1274535277537554432?s=20

**Comment by nalamurapepperlinux** [comment]
動作環境
ideapad s12
PepperMint 10とデュアルブート
CPU　intel Atom N270(32bit)
RAM 1.43GB
ROM HDD 全体・160GB、AlterLinux(xfce)のパーミッション・53GB
SDカード・16GB、AlterLinux(lxde)

使用ISO
https://xn--d-8o2b.com/storage/alter/beta/beta3.1/2020.06.03/alterlinux-xfce-jp-2020.06.03-i686.iso
https://xn--d-8o2b.com/storage/alter/beta/beta3.1/2020.05.26/alterlinux-lxde-jp-2020.05.26-i686.iso

症状
Firefoxのデフォルトの言語が日本語でない。
2つのAlterLinuxをインストールしていますが、どちらも同じ症状を確認しています。

**Comment by Hayao0819** [comment]
6192b0b9b3d8165a78878e2f72e3eca50c83a7bf で修正しました
