### ISSUE TITLE
pamacが起動しない

### ISSUE THREAD

**Issue by nalamurapepperlinux** [FascodeNet/alterlinux#108]
症状
GUIでの使用時に、起動しないソフトウェア（パッケージ管理系）がある。
　現在起動しないことを確認しているソフトウェア
・ソフトウェアの追加・削除
・ソフトウェアの更新

「ソフトウェアの更新」をコマンドで起動した様子(lxde)↓
![スクリーンショット 2020-06-24 19-17-27](https://user-images.githubusercontent.com/66727014/85539701-19d1af80-b651-11ea-972a-5a39cf94d759.png)

動作環境
ideapad s12
PepperMint 10とデュアルブート
CPU　intel Atom N270(32bit)
RAM 1.43GB
ROM HDD 全体・160GB、AlterLinux(xfce)のパーミッション・53GB
SDカード・16GB、AlterLinux(lxde)
※2つのAlterLinuxをインストールしていますが、どちらも同じ症状を確認しています。

使用ISO
https://xn--d-8o2b.com/storage/alter/beta/beta3.1/2020.06.03/alterlinux-xfce-jp-2020.06.03-i686.iso
https://xn--d-8o2b.com/storage/alter/beta/beta3.1/2020.05.26/alterlinux-lxde-jp-2020.05.26-i686.iso

**Comment by Hayao0819** [comment]
`yay -Q | grep pamac`で現在のバージョンを教えて下さい

**Comment by nalamurapepperlinux** [comment]
lxdeはpamac-aur 9.5.5-1です。

**Comment by nalamurapepperlinux** [comment]
xfceも同じバージョンでした。

**Comment by Hayao0819** [comment]
次のバージョンではi686で、`pamac`の代わりに`gnome-packagekit`が使用されます
