### ISSUE TITLE
AlterLinuxにarmアーキテクチャのサポートをしてほしい

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#110]
AlterLinuxにはないarmアーキテクチャのサポートを行ってほしい
armのサポートがされればラズベリーパイなどの一部のハードウェアも動作するようになるため強く希望いたします。

**Comment by naoko1010hh** [comment]
https://twitter.com/nexryai/status/1275909358426058752?s=20
Raspberry Piのサポートしてほしいとの声

**Comment by Hayao0819** [comment]
Arch Linux ARMのパッケージを流用する形になりますが、配布形式はtarballのみになります
AlterISO3ではtarball形式のビルドが試験的に追加されています
