### ISSUE TITLE
AlterISOでAURパッケージ使用できるようにしてほしい

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#111]
AlterISOでは2020/06/26現在ではAURパッケージを適用するにはリポジトリを構築しそこにAURパッケージを登録する必要があるためハードルが少し高い状態です。
AlterLinux派生のLinuxディストーションを普及させるためには少しでもハードルを下げるべきです。
ご検討の程よろしくお願いいたします

**Comment by kokkiemouse** [comment]
alteriso3-aurブランチにて仮対応しました。

**Comment by Hayao0819** [comment]
0c34bd5e52bcfe7274d56a0205d5512830cf2f0a で`alteriso3`にマージされました
