### ISSUE TITLE
AlterLinux i3版 にてpacmanのリポジトリデータベースの更新に失敗する

### ISSUE THREAD

**Issue by 32x-k** [FascodeNet/alterlinux#112]
qemuでの仮想環境にインストールしたところ発生しました。　sudo pacman -Sy　を実行すると ファイル　’core db' を〜から取得するのに失敗しました：The requested URL 404 returned error: 404　とエラーを出し続けてリポジトリデータベースの更新に失敗します。　インターネットに正常に接続されていることは ping コマンド と yayが使用できたことから確認しています。

**Comment by watasuke102** [comment]
ビルドした際のコマンドをお願いします

**Comment by 32x-k** [comment]
sudo ./build.sh -d i3　でビルドしました。　
![image](https://user-images.githubusercontent.com/59412454/85862245-77eec600-b7fc-11ea-8289-dea23159740c.png)　このようなエラーメッセージがずっと流れ続けています。

**Comment by watasuke102** [comment]
/etc/pacman.d/mirrorlist はありますか？

**Comment by 32x-k** [comment]
![image](https://user-images.githubusercontent.com/59412454/85863925-c9985000-b7fe-11ea-9fe5-5c579f000bd6.png)
　無いみたいです。

**Comment by 32x-k** [comment]
![image](https://user-images.githubusercontent.com/59412454/85864452-82f72580-b7ff-11ea-80b8-f6fe5f9daa3a.png)
すみませんsudo付けて実行したら見つかりました。

**Comment by watasuke102** [comment]
`sudo chown ユーザー名 mirrorlist`
`sudo chown ユーザー名 mirrorlist-alter`するとどうなりますか？

**Comment by watasuke102** [comment]
おそらくpacman.confがAlterのものになっていないのが原因です

**Comment by watasuke102** [comment]
8611c9c で修正されたことを確認しました
