### ISSUE TITLE
i3版インストール時に特定の位置で停止する

### ISSUE THREAD

**Issue by watasuke102** [FascodeNet/alterlinux#113]
`sudo calamares`によってインストールを開始した後、93%で止まる
使用ISO: alterlinux-i3-2020.06.26-x86_64.iso（`sudo ./build.sh i3`によってビルド）

（停止時のターミナルの表示）
![Screenshot_20200626_223002](https://user-images.githubusercontent.com/36789813/85863204-cbaddf00-b7fd-11ea-8cb9-350dcb88a8ca.png)

**Comment by watasuke102** [comment]
本日ビルドしたisoでは止まりませんでしたが、タイムゾーンのエラーは変わらず表示されました

**Comment by Hayao0819** [comment]
タイムゾーンの問題は改めてIssueを立ててください
