### ISSUE TITLE
セカンドディスプレイの壁紙がLXDE標準のものになっている。

### ISSUE THREAD

**Issue by nalamurapepperlinux** [FascodeNet/alterlinux#114]
**症状**
i686環境でデュアルモニターにしたとき、セカンドディスプレイの壁紙がLXDE標準のものになっている。
![スクリーンショット 2020-06-29 21-30-37](https://user-images.githubusercontent.com/66727014/86007803-e3ca6c00-ba52-11ea-96f0-838c97a385ca.png)

**動作環境**
ideapad s12
PepperMint 10とデュアルブート
CPU　intel Atom N270(32bit)
RAM 1.43GB
ROM HDD 全体・160GB、AlterLinux(xfce)のパーミッション・53GB
SDカード・16GB、AlterLinux(lxde)
・モニターとD-Subで接続

**使用ISO**
https://xn--d-8o2b.com/storage/alter/beta/beta3.1/2020.05.26/alterlinux-lxde-jp-2020.05.26-i686.iso

**Comment by Hayao0819** [comment]
alterlinux-wallpapers 5.0-3で修正しました。
