### ISSUE TITLE
AlterISOで[build.sh]    Info Building mkalteriso...と表示された後に終了される

### ISSUE THREAD

**Issue by YYTU-Aqua** [FascodeNet/alterlinux#115]
![image](https://user-images.githubusercontent.com/66307999/86573039-bf204800-bfae-11ea-9084-e8e4c68323a3.png)
このようになってうまくビルドが出来ませんでした
AlterのXfceのチャンネルを使用してビルドをしても出来ませんでした

**Comment by watasuke102** [comment]
[こちら](https://github.com/FascodeNet/alterlinux/blob/dev-stable/docs/jp/BUILD.md)に書いてあるパッケージはインストールされていますか？
`sudo pacman -S --needed git make arch-install-scripts squashfs-tools libisoburn dosfstools lynx archiso`

**Comment by YYTU-Aqua** [comment]
インストールされていますがいくつかのパッケージでi686についてのエラーが出されていました

**Comment by watasuke102** [comment]
`git submodule update --init --recursive`をしてみてください

**Comment by YYTU-Aqua** [comment]
`fatal: destination path '/home/yytu/alterlinux/system/cpp-src/mkalteriso' already exists and is not an empty directory.
fatal: clone of 'git@github.com:FascodeNet/mkalteriso.git' into submodule path '/home/yytu/alterlinux/system/cpp-src/mkalteriso' failed
Failed to clone 'system/cpp-src/mkalteriso'. Retry scheduled
fatal: destination path '/home/yytu/alterlinux/system/cpp-src/mkalteriso' already exists and is not an empty directory.
fatal: clone of 'git@github.com:FascodeNet/mkalteriso.git' into submodule path '/home/yytu/alterlinux/system/cpp-src/mkalteriso' failed
Failed to clone 'system/cpp-src/mkalteriso' a second time, aborting
`
とエラーが出ます

**Comment by Hayao0819** [comment]
詳細を表示するために`build.sh`を`-x`を付けて実行してみてください。

**Comment by YYTU-Aqua** [comment]
`[build.sh]    Info Building mkalteriso...
+ [[ true = true ]]
+ make mkalteriso
(cd system/cpp-src/mkalteriso/build ; cmake -GNinja .. ; ninja -j4 ; cp -f mkalteriso ../../../)
CMake Error: The source directory "/home/yytu/alterlinux/system/cpp-src/mkalteriso" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.
ninja: error: loading 'build.ninja': No such file or directory
cp: 'mkalteriso' を stat できません: そのようなファイルやディレクトリはありません
make: *** [Makefile:56: mkalteriso] エラー `
多分ここらへんだと思います

**Comment by YYTU-Aqua** [comment]
system/mkalterisoが入っていないようです

**Comment by YYTU-Aqua** [comment]
![image](https://user-images.githubusercontent.com/66307999/86585257-1e875380-bfc1-11ea-99b0-d7b9f1aa446e.png)

**Comment by Hayao0819** [comment]
`system/mkalteriso`はバイナリなので自動でビルドされます
今はその過程で問題が発生しているようです
`--shmkalteriso`オプションでC++版ではなくSH版を試用できますので、暫定的な対処にはなると思います
`config.any`や`default.conf`の`shmkalteriso`を`true`にすると設定を恒久化できます
