### ISSUE TITLE
xanmodカーネルを指定してビルドしたisoにてインストールに失敗する

### ISSUE THREAD

**Issue by 32x-k** [FascodeNet/alterlinux#116]
build.shにて　sudo ./build.sh -j -u x -k xanmod -o ~/ lxde
でビルドしたところiso自体のビルドには成功しましたが、インス
トールの途中でエラーが発生してインストールできません。
![image](https://user-images.githubusercontent.com/59412454/86896222-a21b7e80-c140-11ea-990b-b3e88b78d106.png)

　環境　qemu上の仮想マシン
    
　ビルドしたisoとsha256,md5をGoogleドライブにアップロードしました。　[googleドライブ](https://drive.google.com/drive/folders/1dmRiFUjMmWF-qb7tkwUaVkuQCFYlXxu_?usp=sharing)

**Comment by Hayao0819** [comment]
AlterISO側に問題は見つかりませんでした。
ArchLinux側の問題[FS65725(https://bugs.archlinux.org/task/65725)だと思われますので暫定的な対処として`alter-stable`リポジトリにて`kmod`パッケージを`26-3`にバージョンダウンしました。
これは`mkinitcpio`のバグで、既にGit上では修正されていますが、まだ新しいバージョンは正式にはリリースされていません。（おそらく重要なパッケージで検証を入念に行う必要があるため）
もし`pacman.conf`でリポジトリの優先度を変更したり、リポジトリを無効化していたりすると`kmod`のバージョンダウンが行われない可能性があるので非公式チャンネルの場合は中止してください。
