### ISSUE TITLE
pacmanのデータベースの情報が古い?

### ISSUE THREAD

**Issue by aoisensi** [FascodeNet/alterlinux#117]
`alterlinux-lxde-2020.06.16-x86_64.iso`
からAlterLinuxをインストールし、`pacman -Syuu` しようとするとパッケージをダウングレードしようとします
![スクリーンショット 2020-07-09 16-09-52](https://user-images.githubusercontent.com/1350990/87008699-1caad380-c1ff-11ea-9be2-e171b0543e4f.png)

**Comment by Hayao0819** [comment]
ライブ環境や起動直後ではデータベースが存在しなかったり、古かったりします
また、使用されているミラーの更新が遅いのかもしれません
現在AlterLinuxでは全てのパッケージリポジトリを有効化しているため、そのような差異が発生する可能性があります
Arch Linux と同様の手順でミラーリストの最適化を起こなうと良いかもしれません

しかし、もし日本語版を使用しているようでしたら、本来ならミラーは日本のミラーに最適化されているはずです

**Comment by aoisensi** [comment]
日本語版を使用したところ解決しました
