### ISSUE TITLE
解像度に1366x768の選択肢を追加してほしい

### ISSUE THREAD

**Issue by Risechocolate** [FascodeNet/alterlinux#118]
ノートPCなどでよく使われる1366x768を追加してほしい。

**Comment by Hayao0819** [comment]
そのハードウェアが対応していれば表示されるはずです
イメージファイルのファイル名（バージョン）とエディション（デスクトップ環境とアーキテクチャ）などを教えてほしいです
また、その問題が発生した機種や環境も教えてくだだい
