### ISSUE TITLE
viが入ってないのでsudoeditがデフォルトで使えない

### ISSUE THREAD

**Issue by aoisensi** [FascodeNet/alterlinux#119]
viをデフォルトで入れるか`$EDITOR`を変えたほうがいい??

**Comment by Hayao0819** [comment]
環境変数`EDITOR`を使用して修正することになりましたが、エディター戦争不可避なので修正にはしばらく時間が掛かりそうです

**Comment by Hayao0819** [comment]
アンケートの結果`nano`に決定しましたので、 8cce75b026f18f7749a7404f8944f50445a74d5a でデフォルトとして設定しました。
