### ISSUE TITLE
AlterISOやAlterLinuxにミラーリポジトリを登録できるようにしてほしい

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#120]
山D鯖のリポジトリ鯖ダウンが頻発して起こるようになったためOSDNリポジトリと山D鯖両方のリポジトリを比較して動いているリポジトリを自動選択するような機能をAlterISOやAlteLinux等に機能追加してほしい
https://twitter.com/Fascode_SPT/status/1284016546369507328?s=20

**Comment by Hayao0819** [comment]
https://github.com/FascodeNet/alterlinux/commit/a71aab94c8a4707363b85ccf29511326e20c3f42 で既にOSDN等のミラーリポジトリを追加済みです
pacmanの機能として既に存在しています
