### ISSUE TITLE
特定のNVIDIAのGPUで起動しない

### ISSUE THREAD

**Issue by nexryai** [FascodeNet/alterlinux#125]
nvidiaのグラフィックボード（palit社製 GT730）使用時、インストール直後の環境で初期ramディスクのロード中に画面が崩壊して起動しません...

![20200730_001031.jpg](https://user-images.githubusercontent.com/61890205/88817938-19e94000-d1f9-11ea-941c-a5fa7bf7cca2.jpg)

環境
dell optiplex790 i7-2600
グラフィック　Palit nvidia GT730 GDDR5 1024MB（ https://www.palit.com/palit/vgapro.php?id=2343&lang=jp )

AlterLinux beta3.1 alterlinux-xfce-2020.06.16-x86_64.iso

他のグラフィックボード（512MB AMD RADEON HD 6350、またはintel内蔵グラフィック) に替えると正常に作動します。またライブ環境ではnvidiaのグラフィックボードでも正常に作動するようです。

**Comment by Hayao0819** [comment]
AlterLinuxでデフォルトで搭載されている`xf86-video-nouveau`の問題です
上流に報告してください

**Comment by Hayao0819** [comment]
AlterLinuxでデフォルトで搭載されている`xf86-video-nouveau`の問題です
上流に報告してください

**Comment by nexryai** [comment]
了解です。ありがとうございます

**Comment by Hayao0819** [comment]
Alter Linux 20Q2.4.0 RC1で起動モードにSafe graphicを追加しました
そちらで起動を試してみて下さい

**Comment by nexryai** [comment]
試してみたところライブ環境ではseaf Graphicsを使用し正常に起動、インストールできましたがやはりインストール後の環境だとseaf Graphicsオプションが無く同様の症状で起動しなくなるようです。

**Comment by Hayao0819** [comment]
インストール後のGrubで`E`キーを押して編集モードに入り、`linux /boot/...`の最後の行に`nomodeset`を追加して起動してください。そうするとセーフモードで起動するのでArchLinux公式のNVIDIAドライバをインストールしてください。
その後は純正ドライバが動作するので`nomodeset`は必要ないと思います。

**Comment by nexryai** [comment]
ありがとうございます。無事セーフモードで起動しコマンドラインから `sudo pacman -S nvidia `  を使用してドライバーをインストールし起動するようになりました。しかしこちらの問題かもしれませんがstartxしてもxinitしてもxorgが起動できずデスクトップが表示できません。ターミナルは正常なので色々試してみます
