### ISSUE TITLE
README_jp.mdを_jaに変更して欲しい

### ISSUE THREAD

**Issue by ghost** [FascodeNet/alterlinux#127]
jpは日本国という地域を表すコードであり、日本語を表すコードではないため。
README_ja.mdに変更してはどうでしょうか。

https://github.com/FascodeNet/alterlinux/blob/master/docs/README_jp.md

**Comment by Hayao0819** [comment]
既にこのファイルへのリンクが存在している以上、ファイル名を変更するとリンク切れを起こす可能性が高くなるため、現在は変更する予定はありません。

**Comment by aoisensi** [comment]
シンボリックリンクを貼るのはどうでしょう?

**Comment by Hayao0819** [comment]
そこまでしてファイル名称の変更を行う意味が無いように思います
