### ISSUE TITLE
/usr/local以下を空にする

### ISSUE THREAD

**Issue by doc382x** [FascodeNet/alterlinux#128]
/usr/local以下にあるバイナリやライブラリをパッケージ化して、パッケージマネージャーの制御下に置いてはどうでしょうか。
/usr/localは管理者がプログラムを後から追加する場所であり、プリインストールする場所ではないと思います。

**Comment by Hayao0819** [comment]
（今ちょうどその作業を進めていたところです）なんというタイミング...

**Comment by Hayao0819** [comment]
（今ちょうどその作業を進めていたところです）なんというタイミング...

**Comment by Hayao0819** [comment]
1034dd66425bcfbd9295e33bd0553982e1ac2a29 で別のパッケージに分離しました
