### ISSUE TITLE
i3 Thunarを開くショートカットを追加してほしい

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#140]
Thunarを開くショートカットが存在していると使いやすくなるため追加してほしいです。

環境
仮想環境64bit

使用ISO
https://山d.com/private/alter/i3-last/alterlinux-i3-jp-2020.07.31-94bef15-x86_64.iso

**Comment by watasuke102** [comment]
863561a で追加しました
ファイルマネージャをmod+Shift+Fで起動できます
