### ISSUE TITLE
i3のコンフィグが重複している

### ISSUE THREAD

**Issue by watasuke102** [FascodeNet/alterlinux#141]
`skel/.config/i3/config` がairootfs.i686とx86_64にあり、その大部分が同一なので、airootfs.anyにまとめてどうにかする

**Comment by watasuke102** [comment]
b49c333 で修正しました

**Comment by Hayao0819** [comment]
Issue-141ブランチでのコミットはどうなりました？

**Comment by watasuke102** [comment]
devにマージされました
