### ISSUE TITLE
 FascodeNetwork 二次創作ガイドラインが自由なライセンスではない

### ISSUE THREAD

**Issue by doc382x** [FascodeNet/alterlinux#144]
FascodeNetwork 二次創作ガイドラインは自由なライセンスではありません。
自由なソフトウェアであるLinuxディストリビューションの公式キャラクターのライセンスとして不適切ではないでしょうか。

* 年齢制限、および閲覧者に不快感をもたらす可能性のある創作をする場合、相応の対処（隠す、注意書きを添える等）をする
* 過度に公序良俗に反する又は反社会的な表現を含めない
* 第三者の権利を侵害しない
* 特定の思想・信条の発信を目的とした表現を含めない
* 本コンテンツの二次創作であることを概要・説明欄や作品本体等に明記し、誤認のないようにする

このうち、最後の一つを除く4つはGNUプロジェクトの「[基本的な自由](https://www.gnu.org/philosophy/free-sw.html)」と相容れないものであると思います。
勝手に商用利用できないのも問題です。

クリエイティブ・コモンズであるとか、GFDLにしてはどうでしょうか。

**Comment by doc382x** [comment]
「第三者の権利を侵害しない」および「特定の思想・信条の発信を目的とした表現を含めない」は第〇の自由である『どんな目的に対しても、プログラムを望むままに実行する自由』に反します。

**Comment by naoko1010hh** [comment]
この度issueを立てていただきありがとうございます。
今回のissueをデザイン班や開発者などと検討したところ、概ね**今までと同じ形という結論**になりました。

しかし、以前から分かりづらい点が多々あったため、FascodeNetwork 二次創作ガイドラインのいくつかの内容をわかりやすい内容へ変更させていただきました。

また、今回の報告いただいたissueの内容はFascodeNetwork全体の内容のため、今後はウェブサイトのお問い合わせページや公式サポートTwitter (@fascode_spt)のダイレクトメッセージにご報告いただけると幸いです。
お手数おかけいたしますがよろしくお願いいたします。

**Comment by doc382x** [comment]
> 概ね今までと同じ形という結論になりました。

それは自由ソフトウェアに対する冒涜です。

適切な場で議論をしたいと考えているのですが、FascodeNetwork全体のメーリングリストやフォーラムはありますか？

**Comment by doc382x** [comment]
> 今回のissueをデザイン班や開発者などと検討したところ
どこで検討したのでしょうか？非公開の場で、一部の人のみで議論するのはもはやオープンソースであるとか自由であるとは言えないのではないのではないでしょうか？

プロジェクトの根幹に関わる問題なのに、それを公の場で議論せず、メールやダイレクトメッセージでするのは不適切ではないでしょうか？

BSDベースに変更するのも一つの手だと思います。

**Comment by Hayao0819** [comment]
オープンソースはあくまでもソフトウェアのソースコードを自由に利用可能にするだけです。決してプライバシーを侵害して良いものではありませんし、開発チーム全体を完全にオープンにするわけではありません。あくまでもソフトウェアにのみ適当されるものです。我々の全てをオープンにするわけでもありません。オープンソースを拡大解釈するのはやめてください。

**Comment by naoko1010hh** [comment]
Alter Linux自体はGPLでライセンスされていますが、二次創作物のライセンスを行う権利並びにその素材に関する権利はFascodeNetwork・その著作者が保持しております。
それらに関してはGNUプロジェクトの主張する「自由」なライセンスにする義務はありません。
また，それに関する判断権はFascodeNetworkが保持しております。
不満がある場合は二次創作向けの著作物を使用しないでください。
この返信を以て本件に関する最終の回答とさせていただきます。
これ以上二次創作ライセンスの件に関して反論等されるようでしたらブロックさせていただく場合がございますのでご了承ください。
また以前も申し上げた通り本件はAlter Linuxの問題ではないため、お問い合わせページ等からご報告いただけると幸いです。
