### ISSUE TITLE
ウェルカムページのタブなし、ありを統一していない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#145]
ライブ環境でデスクトップのアイコンをクリックすると表示されるやつと、
インストール後に表示されるウェルカムページまたはウィンドウのタブありなしが統一されていないので統一してほしい

![VirtualBox_web_04_08_2020_15_17_29](https://user-images.githubusercontent.com/50263013/89263054-8c2fa980-d66b-11ea-8f56-2113bd01af2f.png)
![VirtualBox_web_04_08_2020_15_32_43](https://user-images.githubusercontent.com/50263013/89263058-8d60d680-d66b-11ea-887f-93efc7fc0e88.png)

環境
仮想環境64bit
使用ISO
https://山d.com/private/alter/rc1-alpha1/alterlinux-cinnamon-jp-2020.08.01-0f7c3f0-x86_64.iso

**Comment by Hayao0819** [comment]
9eb24a0bbcac556bd71aa346e9a796f0f0fc8fbd で直接ブラウザを起動するのではなくスクリプトを経由する用に変更しました。日本語と英語で分離させていたのを解消し、言語とアーキテクチャに関わらず統一しました
