### ISSUE TITLE
cinnamonライブ環境で画面ロックをするとログインできなくなる

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#147]
ライブ環境で操作ミスなどで画面ロック行ってしまうとパスワードがわからずにログインできなくなります。
ライブ環境では画面ロックを無効化スべきかと思います。
もしくはライブ環境のパスワードをから文字にするとか？（Linuxだとできないかも？）

![VirtualBox_web_04_08_2020_16_11_45](https://user-images.githubusercontent.com/50263013/89264062-4542b380-d66d-11ea-9ccf-97b89ec8e69c.png)

環境
仮想環境64bit
使用ISO
https://山d.com/private/alter/rc1-alpha1/alterlinux-cinnamon-2020.08.01-0f7c3f0-x86_64.iso

**Comment by Hayao0819** [comment]
[これらのコミット](https://github.com/FascodeNet/alterlinux/compare/9eb24a0bbcac556bd71aa346e9a796f0f0fc8fbd...d9545f1ebf2d6699b356a98bed4239317090246d)でスクリーンのロックを無効化しました
