### ISSUE TITLE
インストール時に実行しているコマンドのログが出るようにしてほしい

### ISSUE THREAD

**Issue by sarukiti** [FascodeNet/alterlinux#149]
長い間かかる処理の際にフリーズしているのではないかという疑念を払拭するために有効だと思われます

![スクリーンショット_2020-08-06_05-03-23](https://user-images.githubusercontent.com/47556340/89405609-d2156c00-d756-11ea-8ada-512b5f0faa2b.png)
↑三角をクリックするとターミナルの表示が出てくるとか

![スクリーンショット_2020-08-06_05-05-12](https://user-images.githubusercontent.com/47556340/89405715-fc672980-d756-11ea-9971-a4abe1711b65.png)
↑GPartedの詳細のようなものを実装できないかなと

**Comment by Hayao0819** [comment]
上流（Calamares）へ機能リクエストを行って下さい。
