### ISSUE TITLE
Alter xfce app launch delay

### ISSUE THREAD

**Issue by mrneilypops** [FascodeNet/alterlinux#158]
Some windows take a long time to open. A good example is settings from the bottom dock. It is taking about 7 seconds for the settings window to fully open when launched. This happens on nouveau and nvidia drivers. I have other xfce Arch distros installed and do not have this problem. Any ideas what I might try to resolve this issue? It is also present if I disable xfce window compositor.

**Comment by Hayao0819** [comment]
I knew the window was slow to open but I thought it was simply a performance issue.
The problem also occurs when started on VirtualBox.
If I change the NVIDIA driver to an official proprietary one, will that fix the problem? Also, please tell us the specific computer performance such as GPU.

**Comment by mrneilypops** [comment]
Hi,
I don't know if changing the nvidia driver to official will help. Maybe I will try that at some point. System specs attached. It is an old computer but I have multiple xfce installs and Alter is the only one at this time with this issue.

System:    Host: alter Kernel: 5.7.12-zen1-1-zen x86_64 bits: 64 Desktop: Xfce 4.14.2 
           Distro: Alter Linux 
Machine:   Type: Desktop Mobo: ASUSTeK model: F1A55-M v: Rev X.0x 
           serial: <superuser/root required> BIOS: American Megatrends v: 1105 date: 08/31/2012 
CPU:       Topology: Quad Core model: AMD A6-3670 APU with Radeon HD Graphics bits: 64 type: MCP 
           L2 cache: 4096 KiB 
           Speed: 803 MHz min/max: 800/2900 MHz Core speeds (MHz): 1: 800 2: 1087 3: 1126 4: 801 
Graphics:  Device-1: NVIDIA GP107 [GeForce GTX 1050 Ti] driver: nvidia v: 450.57 
           Display: x11 server: X.org 1.20.8 driver: nvidia 
           unloaded: fbdev,modesetting,nouveau,vesa resolution: <xdpyinfo missing> 
           Message: Unable to show advanced data. Required tool glxinfo missing. 
Audio:     Device-1: AMD FCH Azalia driver: snd_hda_intel 
           Device-2: NVIDIA GP107GL High Definition Audio driver: snd_hda_intel 
           Sound Server: ALSA v: k5.7.12-zen1-1-zen 
Network:   Device-1: Realtek RTL8111/8168/8411 PCI Express Gigabit Ethernet driver: r8169 
           IF: enp4s0 state: up speed: 1000 Mbps duplex: full mac: 14:da:e9:ed:13:d9 
Drives:    Local Storage: total: 1.09 TiB used: 7.19 GiB (0.6%) 
           ID-1: /dev/sda vendor: SanDisk model: Ultra II 240GB size: 223.57 GiB 
           ID-2: /dev/sdb vendor: SanDisk model: SSD PLUS 480GB size: 447.14 GiB 
           ID-3: /dev/sdc vendor: SanDisk model: SSD PLUS 480 GB size: 447.14 GiB 
Partition: ID-1: / size: 439.12 GiB used: 7.19 GiB (1.6%) fs: ext4 dev: /dev/sdb1 
Swap:      Alert: No Swap data was found. 
Sensors:   System Temperatures: cpu: 19.0 C mobo: N/A gpu: nvidia temp: 31 C 
           Fan Speeds (RPM): N/A gpu: nvidia fan: 20% 
Info:      Processes: 174 Uptime: 2m Memory: 7.75 GiB used: 564.8 MiB (7.1%) Shell: Zsh 
           inxi: 3.1.04

**Comment by Hayao0819** [comment]
I think it's an upstream issue, but it doesn't occur in other distributions, is it true?
We will continue to investigate this issue to fix it, but it may take a long time to fix it.

**Comment by mrneilypops** [comment]
This does not occur in other xfce distros I have installed.
I will stay tuned...

**Comment by Hayao0819** [comment]
Will it happen with the latest RC1?

**Comment by mrneilypops** [comment]
Good point. I found the RC1 earlier. I will test asap. Thanks.

**Comment by Hayao0819** [comment]
This issue has been fixed with an Xfce update
