### ISSUE TITLE
ライブ起動時のGRUBで再起動を行なうことができない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#159]
ライブ起動時のGRUBで再起動を行おうとすると下記のスクリーンショットのように995エラーが出て行なうことができないです。

![image](https://user-images.githubusercontent.com/50263013/89726675-130fc800-da58-11ea-9755-7aef65fb3ac0.png)
![image](https://user-images.githubusercontent.com/50263013/89726680-2753c500-da58-11ea-9b09-228bcf3da948.png)

使用ISO
https://山d.com/private/alter/rc1-alpha2/alterlinux-i3-2020.08.08-3d8b2d5-x86_64.iso
検証環境VirtualBox64bit

**Comment by watasuke102** [comment]
Windowsホスト上のVirtualBox 6.1.8 （64Bit）で同様のisoを使用し検証しましたが、正常に再起動が出来ました

**Comment by naoko1010hh** [comment]
なるほど、、、、自宅に戻ったらもう少し検証したいと思います。

**Comment by watasuke102** [comment]
Arch Linux上のVirtualBox 6.1.12でも正常に再起動することを確認しました
左上のアイコンを見るにOS設定がUbuntuなので、それが原因かと思って検証しましたが関係ないようです

**Comment by naoko1010hh** [comment]
i3インストール後に再起動を行った後の再起動選択で発生したので
そのへんももう少し検証を行いたいと思います。

**Comment by naoko1010hh** [comment]
再度インストールし直して同じ状況が発生するかと思いましたが発生しませんでした。申し訳ありません
