### ISSUE TITLE
i3 追加してほしいショートカットがある

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#162]
i3wmエディションのデバックを行っていた際に2個のショートカットがあると非常に便利になるなーと思いましたのでissueを建てさせていただきます。

1つ目はアクティブウィンドウの切り替えショートカット
2つ目はThunarの起動ショートカット

ご検討のほどよろしくお願いいたします

**Comment by watasuke102** [comment]
1. mod+Shift+上下左右キー
2. mod+Shift+F

以上実装済みです。
