### ISSUE TITLE
i3 ヘルプの英語リンクの設定がミスっている

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#164]
英語のリンクの＃ホニャララが大文字になっている部分があるためid属性と一致せず飛ぶことができない
日本語は目次に飛べるのにもかかわらず英語に飛べないのは問題かと思いまず。
この画面はmod + シフト + Hで出しました。

![image](https://user-images.githubusercontent.com/50263013/89751944-35afe880-db0d-11ea-8633-1d2abe8f5a7f.png)

検証環境
32bit仮想環境VirtualSex
検証ISO
https://山d.com/private/alter/i3-2a31e2d/alterlinux-i3-2020.08.10-2a31e2d-i686.iso

**Comment by watasuke102** [comment]
修正済みです
