### ISSUE TITLE
i3-wm: VimやHtopがSoftware Launcherから起動できない

### ISSUE THREAD

**Issue by goahi** [FascodeNet/alterlinux#165]
**現象**
Software LauncherからVimやHtopなどのターミナルで開くアプリケーションが「Failed to find a suitable terminal」と出て起動できない。

**再現方法**
1. mod + D でSoftware Launcher を表示
2. VimやHtopを起動

**スクリーンショット**
![image](https://user-images.githubusercontent.com/67847553/90095027-79535e00-dd6a-11ea-9a98-4b8825cdba84.png)

**環境**
- Virtual Box 6.1.10_Ubuntu r138449 
- Alter Linux i3wm 20Q1.4.0 RC1
- [ISOのリンク](https://ja.osdn.net/projects/alterlinux/downloads/73447/alterlinux-i3-2020.08.10-x86_64.iso/) 

**やったこと**
`yay -S xterm`でXtermを導入すると正常に起動できる。ただ、文字などのカスタマイズはされていない状態になるのでそこの設定は必要。

**その他**
解決方法はもっとスマートな方法はあるのかもしれませんが、一応報告はしておきます。これからも開発、頑張ってください。

**Comment by watasuke102** [comment]
xtermは #129 で削除されたので、標準のターミナルであるsakuraで起動できるようにしてみます

**Comment by watasuke102** [comment]
bf14daf でsakuraから起動できるように変更しました
~/.zshrcに`export TERMINAL=/usr/bin/sakura`と記述すればrofiからhtop等をsakuraで起動させることが可能です
