### ISSUE TITLE
alterlinux/docs/jp/BUILD.md　に脱字がある

### ISSUE THREAD

**Issue by 32x-k** [FascodeNet/alterlinux#168]
![image](https://user-images.githubusercontent.com/59412454/90337901-91ec9e00-e020-11ea-828b-17f46e35125f.png)
正しくは　”主なオプションは以下のとおりです。完全なオプションと使い方は./build -hを実行して下さい。”　になると思います。

**Comment by Hayao0819** [comment]
近いうちの修正します
また、こういった誤字脱字はプルリクエストを頂けるとありがたいです。

**Comment by 32x-k** [comment]
わかりました
