### ISSUE TITLE
Calamares on i3wm edition failed to add host name

### ISSUE THREAD

**Issue by drmarwat** [FascodeNet/alterlinux#169]
Calamares failed to add host name , the hostname remained at alterlive on installed alterlinux i3 and I had to manually change it to my desired one.

Polybar nm-applet does not show any wirless networks at all to choose and connect , I had to install lxpanel and run lxpanel from terminal and then could connect wireless on my laptop with nm-applet .

**Comment by Hayao0819** [comment]
Thank you for reporting. Whenever possible, include only one report in an issue. It's easier to track down the issue.

**Comment by watasuke102** [comment]
Network settings can be configured through the System Configuration Manager opened by mod+B.
Push mod+B → type "2" (Network)
