### ISSUE TITLE
Gnome版でプラグインが適用されていない

### ISSUE THREAD

**Issue by minus102** [FascodeNet/alterlinux#171]
インストール前、突然ロック画面が表示されログインするとプラグインが適用されてない状態のデスクトップが表示される
![コメント 2020-08-17 195043](https://user-images.githubusercontent.com/69842203/90488012-d3d72a80-e16d-11ea-92fa-b1d935c329c7.png)

環境
VirtualBox 6.1.12 r139181
alterlinux-gnome-ja-2020.08.17-8e0c7297-x86_64.iso

**Comment by Hayao0819** [comment]
画面がロックされるというのは数分放置したということでよろしいですか？

**Comment by minus102** [comment]
放置ではなく操作してる状態ですね...

**Comment by minus102** [comment]
えっと
intel Core i5 7200
HD Graphics 620
4GBメモリ
です
