### ISSUE TITLE
Gnome版でBluetooth機器とペアリングするとBluetoothマネージャーがフリーズする

### ISSUE THREAD

**Issue by minus102** [FascodeNet/alterlinux#172]
Gnome版でBluetoothをペアリングするとBluetoothマネージャーがフリーズします
コードが表示されて許可をクリックした瞬間にフリーズします

環境
NEC HZ550/GAB
alterlinux-gnome-ja-2020.08.17-8e0c7297-x86_64.iso

**Comment by minus102** [comment]
Xfce版では正常に動作しました
あとGnome版のClosedbeta2でも正常に動作しました...

**Comment by Hayao0819** [comment]
わかりました。おそらくWayland上での問題です。
