### ISSUE TITLE
GNOME版で特定の操作を行うと標準のGNOMEのアクティビティが表示される。

### ISSUE THREAD

**Issue by 32x-k** [FascodeNet/alterlinux#173]
![image](https://user-images.githubusercontent.com/59412454/90495366-7d72e780-e17f-11ea-9d95-d5703e6aeebf.png)
![image](https://user-images.githubusercontent.com/59412454/90496739-2ff77a00-e181-11ea-9b9e-a64c4f691fe2.png)
windowsキーを押すとこのようにGNOME標準のアクティビティ画面が表示されて、ログアウトなどをするまでそのままになります。

**Comment by Hayao0819** [comment]
修正しました。
