### ISSUE TITLE
gnome版でインストールに失敗する

### ISSUE THREAD

**Issue by 32x-k** [FascodeNet/alterlinux#175]
qemu上の仮想マシンにAlterLinux gnome版をインストールしようとしたところ、以下のエラーが発生してインストールに失敗しました。 
![image](https://user-images.githubusercontent.com/59412454/90507622-283fd180-e191-11ea-9bfc-bac75910b559.png)

使用したISO　[alterlinux-gnome-ja-2020.08.18-278ecb29-x86_64.iso](https://drive.google.com/file/d/1xnWn8HBdTaxi5VljADHfOED14IH9rIOE/view?usp=sharing)

**Comment by Hayao0819** [comment]
修正しました
