### ISSUE TITLE
Inspiron 5570でインストールできない

### ISSUE THREAD

**Issue by rikusen0335** [FascodeNet/alterlinux#181]
UEFIからUSBを選んでインストールしようとしたところ、
画像のようなエラーが出てきてインストールを完了できません。
インストールしようとしているのはAlter i3です。
![IMG_20200824_175837](https://user-images.githubusercontent.com/19174234/91039805-3043b980-e648-11ea-9f84-5ff35411a168.jpg)

**Comment by Hayao0819** [comment]
USBメモリにRufusで焼いていませんか？
EtcherやUSBWriterを使用すると正常に起動します。Rufusなどを私用する場合、「ddモード」を使用してみてください。

**Comment by rikusen0335** [comment]
Rufusで焼いてました。Etcherだとできました、ありがとうございます！
