### ISSUE TITLE
archlinux32-keyringのパッケージがダウンロードできない

### ISSUE THREAD

**Issue by yangniao23** [FascodeNet/alterlinux#184]
**Describe the bug**
パッケージのダウンロード時に404を返す

**スクリーンショット**
![image](https://user-images.githubusercontent.com/47053316/91307779-594f8000-e7e9-11ea-99bf-22e23e34ef45.png)

 - OS:  Alter Linux

**Comment by Hayao0819** [comment]
`yay -Syy`をしてから実行してみて下さい

**Comment by yangniao23** [comment]
何も改善しませんでした

おそらくalter-testingの方を読みに行っているのではないかなと推測している

**Comment by Hayao0819** [comment]
`/etc/pacman.d/mirrorlist-alter`よりサーバを山D.comのみして再検証してみてください。
現在山D.comだけリポジトリデータベースを更新しました。

**Comment by yangniao23** [comment]
すみません，挙動を見るとalter-stableから取得しているみたいです

**Comment by yangniao23** [comment]
Keyring.shの記述を見直し，正常に動作するようにしました。
