### ISSUE TITLE
CPU-Xが起動しない

### ISSUE THREAD

**Issue by hyuoou** [FascodeNet/alterlinux#185]
CPU-Xが起動できませんでした。
![cpu-x](https://user-images.githubusercontent.com/63180765/91436815-cf182200-e8a3-11ea-83d2-612b7fe50c1b.jpg)
環境
VirtualBox
alterlinux-xfce-jp-2020.08.10-x86_64.iso

**Comment by Hayao0819** [comment]
上流の問題だと考えています。[こちらのツイート](https://twitter.com/Fascode_JP/status/1298947503929270273)にもありますが、以下のコマンドを実行すると**暫定的ですが**対処できます。

```bash
sudo ln -s "/usr/lib/libcpuid.so.15" "/usr/lib/libcpuid.so.14"
```

**Comment by Hayao0819** [comment]
リポジトリのパッケージの再ビルドで解決しました
