### ISSUE TITLE
Deepinのライブ環境での警告

### ISSUE THREAD

**Issue by Hayao0819** [FascodeNet/alterlinux#187]
Deepinはライブ環境で常に「insufficient disk space」という警告を出します。

**Comment by lap1sid** [comment]
Plasma版でも同様の警告が出現(スペルは違うが、ディスク容量が不足してると言う意味は同様)

**Comment by Hayao0819** [comment]
ライブ環境上どうしようもないのでどうにかして警告を消すしかない

**Comment by lap1sid** [comment]
こちらPlasma確認したところ通知は無効化できる模様

しかし荒くやってしまうとインストール後の環境で通知されなくなってしまう
