### ISSUE TITLE
neofetch-gitにArch Linux として認識されている

### ISSUE THREAD

**Issue by 32x-k** [FascodeNet/alterlinux#188]
![image](https://user-images.githubusercontent.com/59412454/91654579-fad61a80-eae4-11ea-9b29-fb3844969f06.png)
neofetch-gitをインストールして実行してみたところ、Alterのロゴではなく、Arch Linuxのロゴが表示されました。

**Comment by watasuke102** [comment]
インストールに使用したファイル名をお願いします

**Comment by 32x-k** [comment]
すみません　インストールしてからそれなりに時間が経っている影響で使用したISOを失念してしまったのですが、おそらくalterlinux-lxde-jp-2020.06.03-x86_64.iso　あたりのものを使用したんじゃないかと思います。　RC1じゃないのは間違いないです。

**Comment by kokkiemouse** [comment]
filesystemパッケージが/etc/osreleaseを書き換えるのが原因と思われます...

**Comment by Hayao0819** [comment]
現在 https://github.com/FascodeNet/alterlinux-pkgbuilds/commit/88ab5d7a5bbccef586501fe7cb02991806b2d0ea で`filesystem`パッケージをAlter Linux独自のものに置き換える作業を進めています。重要なパッケージなため、デバッグを繰り返し行っていきます。

**Comment by Hayao0819** [comment]
https://github.com/FascodeNet/alterlinux-pkgbuilds/tree/master/alter-stable/any/filesystemで`filesystem`を正式なパッケージに追加しました。近々リポジトリに反映させます。

**Comment by Hayao0819** [comment]
`x86_64`で`filesystem`パッケージを`alter-stable`に公開しました
