### ISSUE TITLE
Meditの終了ダイアログの翻訳ミス

### ISSUE THREAD

**Issue by exe-furikake** [FascodeNet/alterlinux#192]
meditを保存せずに終了しようとすると、出てくるウィザードの語がおかしいです。
管轄外でしたらすみません。
https://drive.google.com/file/d/1p0_xRpvSeAfFLAkLwqltHTURJ94t31kz/view?usp=sharing
（案）無効→保存せずに終了

**Comment by Hayao0819** [comment]
これはMeditの上流の問題で、AlterLinux側の問題ではありません。
上流へ報告を行って下さい。
