### ISSUE TITLE
-jオプションで間違ったエラーが表示される

### ISSUE THREAD

**Issue by watasuke102** [FascodeNet/alterlinux#197]
alteriso-3-mainlineのbuild.shに-jオプションを付けて実行すると  
`[build.sh]   Error This option is obsolete in AlterISO 3. To use Japanese, use "-g ja".`  
と表示されますが，現在言語を指定するオプションは-lのはずです

**Comment by Hayao0819** [comment]
以前のバージョンのオプションですね...修正しました
