### ISSUE TITLE
qt5ctが起動しない

### ISSUE THREAD

**Issue by menndouyukkuri** [FascodeNet/alterlinux#204]
インストーラーがデスクトップ、メニューのアイコンから起動できません。

発生環境
・Alter Linux RC2のXfce（alterlinux-xfce-jp-2020.10.01-x86_64.iso）及びLXDE（alterlinux-lxde-jp-2020.10.01-x86_64.iso）、Cinnamon（alterlinux-cinnamon-jp-2020.10.01-x86_64.iso）
・VirtualBox 6.1.14 r140239
・intel Core 2 Duo P8700 2.53GHz

追加情報
・-Eオプションを外せば起動できます。

**Comment by Hayao0819** [comment]
`qt5-styleplugins`を再ビルドすると問題は解決します

**Comment by Hayao0819** [comment]
リポジトリのパッケージの`pkgrel`を更新しました
