### ISSUE TITLE
aurbuildというユーザーがインストール後も残ったままになっている

### ISSUE THREAD

**Issue by 32x-k** [FascodeNet/alterlinux#207]
AlterISO3でAURを有効にした状態でビルドするとインストール後もaurbuildというユーザーが残ったままになります　動作には支障ないのですが毎回ログイン時にユーザーを切り替える必要があって面倒なので残らないようにしてほしいです

**Comment by kokkiemouse** [comment]
すでに修正済みのバグです。
![image](https://user-images.githubusercontent.com/39451248/95666230-98b40f00-0b92-11eb-8e33-8e9605200442.png)
