### ISSUE TITLE
Virtualbox環境においてカーネルパニックが発生する

### ISSUE THREAD

**Issue by sarukiti** [FascodeNet/alterlinux#209]
**バグの内容**
起動時にブートアニメーションが出ることなくカーネルパニックが発生する
Alter Linux RC2 Xfce版およびi3版にて確認しました
Beta3.1においては確認できなかったのでRC2のみの問題であると思われます

**再現**
Virtualboxで仮想環境を作成し、初回起動時に発生します

**スクショ**
![image](https://user-images.githubusercontent.com/47556340/95675500-b2853e80-0bf2-11eb-8745-0005d345d335.png)
仮想マシンの構成も載っています

**環境:**
 - OS: Windows 10 64bit 2004
 - VirtualBox 6.1.10 r138449

**Comment by sarukiti** [comment]
VirtualBox 6.1.14 r140239でも当該現象が発生することを確認しました

**Comment by Hayao0819** [comment]
イメージファイルのダウンロードが正常に行われているか、MD5やsha256を使用して確認してください。

**Comment by sarukiti** [comment]
sha256でファイルが正常であると確認しました

**Comment by Hayao0819** [comment]
起動メニュー（syslinux）は起動しますか？セーフグラフィックモードで起動してみてください

**Comment by sarukiti** [comment]
Windowsをクリーンインストールすると治ったのでおま環でした……
お手数おかけし大変申し訳ありませんでした
