### ISSUE TITLE
VNCサーバーとしてうまく接続できない

### ISSUE THREAD

**Issue by Tenazuchi** [FascodeNet/alterlinux#210]
Bugではなく、またalterlinuxの問題でないかもしれないのですが質問いいでしょうか。

alterlinuxにtigervncをインストールし、windowsから接続したいのですがうまく接続できません。参考にしたサイトはarch linuxのtigervncの項目とhttps://linoxide.com/linux-how-to/install-configure-tigervnc-arch-linux/です。よろしかったら、詳細を書こうと思います。

**Comment by Hayao0819** [comment]
Tiger VNCの専門のフォーラムで質問してください。VNCに関する知識はありません。
