### ISSUE TITLE
Hyper-V 2世代で起動しない

### ISSUE THREAD

**Issue by lap1sid** [FascodeNet/alterlinux#212]
## 環境
- Windows 10 Pro 2004 Hyper-V
- Hyper-V 2世代 (UEFI)
- Ryzen 5 3600 (仮想コア数は4)
- 指定RAMは4GB
- ホスト側GPUは GTX1650

## 詳細
* MD5: `f1d56220a8bf029f27400c08f3c25dbc` (`md5sum.exe`より確認)
* ISO: `https://山d.com/storage/alter/release-candidate/rc2/2020.10.09/alterlinux-xfce-2020.10.09-x86_64.iso`
* セキュアブート: オフ
* 仮想ディスク: 未設定

以下のように起動しません。
![image](https://user-images.githubusercontent.com/48173871/96841157-65bd2580-1486-11eb-8da2-6c04ab1ce79f.png)

**Comment by lap1sid** [comment]
ISOはしっかりと設定済み
![image](https://user-images.githubusercontent.com/48173871/96841710-14f9fc80-1487-11eb-88c4-bd48489f467f.png)

**Comment by Hayao0819** [comment]
UEFI環境で起動しないのは既知の問題で、`dev`で既に修正されています。
Beta3.1では発生しないと思います（Archiso v45をマージした際に発生したバグ）

**Comment by lap1sid** [comment]
了解
