### ISSUE TITLE
アップデートすると起動時にエラーが出る。

### ISSUE THREAD

**Issue by Tenazuchi** [FascodeNet/alterlinux#219]
新規インストール直後はきれいな起動画面が出るのですが、アップデートすると途中で以下のようなメッセージが出て、再起動時にエラーが表示されます。
　AlterLinux Xfce 日本語版 64bit20Q3.4.1 RC2、インストール時に自動ログイン、rootとユーザーに同じパスワードを選択しています。PCはVAIO　VGN-CS60B、CPUはP8400です。

![IMG_0510](https://user-images.githubusercontent.com/48636148/101275512-91535f80-37e9-11eb-96c4-5ac7048f9ca9.jpg)
![IMG_0512](https://user-images.githubusercontent.com/48636148/101275533-a9c37a00-37e9-11eb-8873-411643b48f7e.jpg)
![IMG_0513](https://user-images.githubusercontent.com/48636148/101275539-b34ce200-37e9-11eb-873c-11c1a9a3f383.jpg)

　最終的には起動するのですが、エラー表示が出ないようになりますか？

**Comment by Tenazuchi** [comment]
自分はVimを使用しないので、Vimを削除してからアップデートすることで問題を回避することができました。

**Comment by Hayao0819** [comment]
パッケージリポジトリの問題です。現在は修正されています。
