### ISSUE TITLE
Calamaresがusersモジュールのロードに失敗する

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#226]
**Describe the bug**
内部バージョンHayaoビルドXfce4 64Bit 日本語を使用してインストールしようとしたところ
インストールウィザードからインストールできない
モジュールが読み込めない模様？
![IMG_20201224_152359](https://user-images.githubusercontent.com/50263013/103066580-8b88b700-45fc-11eb-8fa0-8c0a1ece53f7.jpg)

ハッシュはあとから追記します

実機AMD Ryzen５ ５６００ｘ
メモリDDR４ ８GB４枚３２ｇｂ
HDD ４台
マザボ ASRock B450M

**Comment by naoko1010hh** [comment]
alterlinux-xfce-ja-2020.12.24-5d084968-x86_64.iso 使用ISO

**Comment by naoko1010hh** [comment]
コマンドラインのログです

alter  alterlive  ~  %  calamares

(calamares:7445): Gtk-WARNING **: 15:33:15.501: module_path にはテーマ・エンジンがありません: "murrine",

(calamares:7445): Gtk-WARNING **: 15:33:15.501: module_path にはテーマ・エンジンがありません: "murrine",

(calamares:7445): Gtk-WARNING **: 15:33:15.502: module_path にはテーマ・エンジンがありません: "murrine",

(calamares:7445): Gtk-WARNING **: 15:33:15.502: module_path にはテーマ・エンジンがありません: "murrine",

(calamares:7445): Gtk-WARNING **: 15:33:15.502: module_path にはテーマ・エンジンがありません: "murrine",

(calamares:7445): Gtk-WARNING **: 15:33:15.502: module_path にはテーマ・エンジンがありません: "murrine",

(calamares:7445): Gtk-WARNING **: 15:33:15.502: module_path にはテーマ・エンジンがありません: "murrine",

(calamares:7445): Gtk-WARNING **: 15:33:15.502: module_path にはテーマ・エンジンがありません: "murrine",

(calamares:7445): Gtk-WARNING **: 15:33:15.502: module_path にはテーマ・エンジンがありません: "murrine",

(calamares:7445): Gtk-WARNING **: 15:33:15.503: module_path にはテーマ・エンジンがありません: "murrine",

(calamares:7445): Gtk-WARNING **: 15:33:15.503: module_path にはテーマ・エンジンがありません: "murrine",
warning: /home/alter/.cache/calamares is not writable
warning: Could not find a standard writable location for log dir, falling back to $HOME
warning: /home/alter/.cache/calamares is not writable
warning: Could not find a standard writable location for log dir, falling back to $HOME
warning: /home/alter/.cache/calamares is not writable
warning: Could not find a standard writable location for log dir, falling back to $HOME
15:33:15 [1]: bool Calamares::ModuleManager::addModule(Calamares::Module*)
    ERROR: Module "users@users" loading FAILED. 
15:33:15 [1]: void Calamares::ModuleManager::loadModules()
    ERROR: Module "users@users" exists but not loaded. 
15:33:15 [1]: void CalamaresApplication::initFailed(const QStringList&)
    ERROR: STARTUP: failed modules are ("users@users", "users@users") 
15:33:16 [0]: unknown file system type  ""  on  "/dev/sda"

**Comment by lap1sid** [comment]
sudo calamares
でログを取ってください

**Comment by Hayao0819** [comment]
`3.2.35-3`で修正しました。上流の`icu`パッケージの更新が原因です
