### ISSUE TITLE
pamac-manager 下部のタスクバーから起動することができない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#227]
pamac-managerが下部のタスクバーから起動することができない
![image](https://user-images.githubusercontent.com/50263013/103068087-c04a3d80-45ff-11eb-83d1-b190845cf87d.png)

使用ISO 内部デバック alterlinux-xfce-ja-2020.12.24-5d084968-x86_64.iso

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB 
MB   B450M Steel Legend

**Comment by Hayao0819** [comment]
修正しました

https://github.com/FascodeNet/alterlinux/commit/9d488e91642b9ba6b28bf1e091db54b35ac3ba15
https://github.com/FascodeNet/alterlinux-xfce-conf/commit/88277e032745184e504e23ab1f2b38a7f8247e4c
