### ISSUE TITLE
yay -Syu が失敗する　

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#228]
スクリーンフェッチをインストールするのに念の為yay -Syuやyay -Syyuを行いアップデートをしようとしたところ正常に動作してないような挙動
インターネットはつながっているのでおそらくバグ？
ドメイン変更によるもの？
詳細は不明

![image](https://user-images.githubusercontent.com/50263013/103068609-d4426f00-4600-11eb-8d02-bd29638e92fa.png)

使用ISO 内部デバック alterlinux-xfce-ja-2020.12.24-5d084968-x86_64.iso

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by Hayao0819** [comment]
これってインストール後の環境ですか？それともインストール後の環境ですか？

**Comment by scarlet-Chun-DH** [comment]
Let's Note環境(もちろん実機)でも同様の問題が生じています。
