### ISSUE TITLE
XDGのディレクトリ名が日本語と英語で混在している

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#229]
どちらかホームディレクトリのディレクトリ名をアルファベットか日本語に統一すべきかと思います。
個人的にはディレクトリ自体はすべてアルファベットでファイルマネージャー（thunar）は日本語表記が理想です。

![image](https://user-images.githubusercontent.com/50263013/103068953-a27dd800-4601-11eb-8cb4-4469ab23a60e.png)

ゴミ箱だけ日本語なのも気になる、、、、
![image](https://user-images.githubusercontent.com/50263013/103069244-53847280-4602-11eb-9dff-40d21cdaf7ca.png)

使用ISO 内部デバック alterlinux-xfce-ja-2020.12.24-5d084968-x86_64.iso

環境
ホストアーキテクチャ 64bit
CPU Ryzen5 5600x
RAM 32GB
HDD 4台 東芝4TB シーゲート 1TB 日立500GB　東芝 1TB
MB B450M Steel Legend

**Comment by Hayao0819** [comment]
どっちも修正できない既知の問題です。

**Comment by naoko1010hh** [comment]
空の隠しファイル置くのはどうでしょう？

**Comment by Hayao0819** [comment]
- Desktopのみ英語→ライブ環境にてCalamaresのアイコンをデスクトップに置くために必要
- サイドバーのゴミ箱が英語→Thunarの仕様のため名前の変更は不可能
- サイドバーのディレクトリ名を日本語にする→可能だがかなりの変更が必要

**Comment by naoko1010hh** [comment]
他の意見人の意見聞きたいところですね


一番下のディレクトリを空ファイルをなどを一時的においてアルファベット化、サイドバー日本語が一番きれいじゃないかなっと思います。

**Comment by Hayao0819** [comment]
> 一番下のディレクトリを空ファイルをなどを一時的においてアルファベット化
これの意味がわかりません。サイドバーの日本語化もDesktopはおそらくできないと思います。
また、この問題はSereneLinux時代に一度議論されている問題なので修正は難しいと思います。

**Comment by naoko1010hh** [comment]
可能だがかなりの変更が必要

との記述があったので提案してみました

空ファイルにつきましてはDesktopショートカットのファイルが置かれているもののみDesktopというディレクトリ名になっていたため空ファイルを置けばなんとかなるのではないかと思い提案してみました

**Comment by Hayao0819** [comment]
空ファイルを置くの意味がわかりません。
[このように](https://github.com/FascodeNet/alterlinux/tree/dev/channels/share/airootfs.any/etc/skel)`airootfs`で直接Desktopファイルを配置しているためこうなっています。これを修正するには[alterlinux-live-tools](https://github.com/FascodeNet/alterlinux-live-tools)を使用して処理する必要がありますが、そこまでするメリットがみられないのでこのままにしてあります。

**Comment by naoko1010hh** [comment]
なるほど、
優先度は低いかもしれませんがやはり見た目的にどうなんだろうって思ってしまいます。

リリース時には治ってると良いなぐらいに思っておきます。

**Comment by Hayao0819** [comment]
- [alterlinux-desktop-file](https://github.com/FascodeNet/alterlinux-live-tools/tree/master/alterlinux-desktop-file)によるファイルのコピーで`skel/Desktop`の完全廃止
- `alterlinux-welcome-page`と同様に`.config/autostart/genicon.desktop`でコマンドを自動実行
- `alterlinux-gtk-bookmarks`の名前を多言語対応

**Comment by Hayao0819** [comment]
5d685dd9cd4839ecf4074a731e4f668fad74fe71 と`alterlinux-live-tools v1.5`(https://github.com/FascodeNet/alterlinux-live-tools/releases/tag/v1.5)で修正しました

**Comment by Hayao0819** [comment]
![VirtualBox_Alter Linux Test_27_12_2020_12_23_17](https://user-images.githubusercontent.com/32128205/103163201-65525980-483e-11eb-8a1c-a8482d221cb0.png)
