### ISSUE TITLE
ビルドしたisoでブートができない

### ISSUE THREAD

**Issue by YYTU-Aqua** [FascodeNet/alterlinux#233]
ビルド環境
VirtualBox
使用iso
alterlinux-xfce-ja-2020.12.30-bcf92d0d-x86_64.iso
ビルドコマンド
sudo ./build.sh xfce
isoのブート時にGRUBは出ますがarchiso.imgがないと言われまたgrubに戻されます

**Comment by Hayao0819** [comment]
ビルド時のログを見せてください。少なくともこちらの環境では同様のソースコード、コマンドでビルドできました

**Comment by YYTU-Aqua** [comment]
すみませんログファイルはどこかに生成されますか？

**Comment by Hayao0819** [comment]
ターミナルに出力されていると思いますが...
ログをファイルに保存する場合は`tee`コマンドを使用してください

**Comment by YYTU-Aqua** [comment]
わかりました

**Comment by YYTU-Aqua** [comment]
[log.txt](https://github.com/FascodeNet/alterlinux/files/5761207/log.txt)

**Comment by Hayao0819** [comment]
この後にビルドしたディスクで起動できないと...ちょっと原因がわからないです。ごめんなさい
isoファイルを焼いたり転送したりした際に破損したとしか...

**Comment by YYTU-Aqua** [comment]
Linux上でisoをマウントしてみましたがarchiso.imgがありませんでした
(ALTER/BOOT/X86_64)

**Comment by Hayao0819** [comment]
起動環境はBIOSです?UEFIですか？

**Comment by YYTU-Aqua** [comment]
BIOSです

**Comment by Hayao0819** [comment]
こちらでビルドしたisoにはarchiso.imgがちゃんとありました...
custom.confなどで設定を変更していたりとかってありますか？

**Comment by YYTU-Aqua** [comment]
何も変更していませんね...

**Comment by Hayao0819** [comment]
isoファイルをどこかにアップロードできませんか

**Comment by YYTU-Aqua** [comment]
http://59.137.150.204/nextcloud/index.php/s/eRCB7FNMQ6e33Gz

**Comment by YYTU-Aqua** [comment]
http://59.137.150.204/nextcloud/index.php/s/KRJ9Mm6zcoTHaBg
遅れてすみません

**Comment by Hayao0819** [comment]
あ、`mkinitcpio`で失敗してる...でもうーん...原因がわからない
