### ISSUE TITLE
pacmanで落ちる

### ISSUE THREAD

**Issue by kokkiemouse** [FascodeNet/alterlinux#234]
# Pacmanちゃんが落ちる
## 実行コマンド
sudo pacman -Syu
## 解説
pacman -Syuするとgpgエラーです...
alterlinux-keyringは最新です。
/etc/pacman.confからalterlinuxの項目を削除したところ正常に更新できたのでリポジトリかgpgキーの問題だと思います...

## ログ
エラー: GPGME エラー: データがありません
:: パッケージデータベースの同期中...
/var/lib/pacman/sync/alter-stable 100%[===========================================================>]  22.07K  --.-KB/s 時間 0.02s    
/var/lib/pacman/sync/alter-stable 100%[===========================================================>]  77.31K   292KB/s 時間 0.3s     
エラー: GPGME エラー: データがありません
エラー: alter-stable の更新に失敗しました (無効または破損したデータベース (PGP 鍵))

**Comment by kokkiemouse** [comment]
# 追加情報
pacman -Uも落ちます...
こんな感じにエラーが出ます...
エラー: 処理の準備に失敗しました (無効または破損したデータベース)

**Comment by lap1sid** [comment]
鍵の有効期限を確認した所問題はありませんでした
他の原因だと思われます

**Comment by kokkiemouse** [comment]
当職もkeyring更新してみましたが駄目でした...
原因がわからないですを

**Comment by llnnn-ux** [comment]
![Screenshot_20210109-232952.png](https://user-images.githubusercontent.com/72482919/104094199-a896d880-52d2-11eb-8bb4-275d1b700266.png)
fascode.pubがimageデータになってないですか？

**Comment by kokkiemouse** [comment]
ﾅﾝｼﾞｬｺﾘｬ

**Comment by kokkiemouse** [comment]
repo.dyama.netのやつ?
それならpgp鍵のはずですが...

**Comment by llnnn-ux** [comment]
https://xn--d-8o2b.com/repo/fascode.pubです

**Comment by kokkiemouse** [comment]
現在使われてない方ですね...
今は
https://repo.dyama.net/fascode.pub
ですので...

**Comment by llnnn-ux** [comment]
あ、そうなんですねごめんなさい

**Comment by lap1sid** [comment]
公開鍵の再生成を試す価値はありそうですね
