### ISSUE TITLE
GNOME版でタッチパッドの設定ができない

### ISSUE THREAD

**Issue by C4NoN424** [FascodeNet/alterlinux#239]
gnome-control-center内のマウスの設定から, タッチパッドの設定を変えることができない
ドライバ xf86-input-synaptics を削除し, xf86-input-libinput をインストールすることで設定が表示され設定変更することが可能になることを確認.

・isoファイルのバージョン
alterlinux-gnome-en-2021.01.26-89b0dea8-x86_64.iso
・動作環境
Sony Vaio SVT13119FJS
CPU: Intel Core i5-3317U
RAM: 6GB

**Comment by kokkiemouse** [comment]
今の所
89b0dea8
以降で該当箇所がないためおそらく未修正です。

**Comment by kokkiemouse** [comment]
7ec12220
未検証ですがxf86-input-libinput を追加しました。

**Comment by Hayao0819** [comment]
このIssueは`xf86-input-synaptics`を削除することは必須ですか？

**Comment by kokkiemouse** [comment]
削除する必要はないですね、多分
