### ISSUE TITLE
typo: ビルドイン -> ビルトイン

### ISSUE THREAD

**Issue by KanchiSato** [FascodeNet/alterlinux#248]
https://github.com/FascodeNet/alterlinux/blame/414b76522e72667512029a5526a9ecf0e14120b9/docs/CONTRIBUTING.md#L7

ビル「ド」インではなく、ビル「ト」インではないでしょうか

参考URL：https://www.gnu.org/software/bash/manual/html_node/Bash-Builtins.html

**Comment by Hayao0819** [comment]
仰るとおりです...報告ありがとうございます
