### ISSUE TITLE
docs/CONTRIBUTING.mdの先頭に英語の行へのリンクを

### ISSUE THREAD

**Issue by yodogawa404** [FascodeNet/alterlinux#250]
リポジトリ直下のREADME.mdに``日本語版はこちらにあります``という記述があるのと同じように
``docs/CONTRIBUTING.md``にも``english version here``のような記述とページ内リンクを入れたほうがわかりやすいのではないでしょうか。

**Comment by Hayao0819** [comment]
提案ありがとうございました。先程更新しました
