### ISSUE TITLE
vscodeの定義に移動(F12)と、xfceドロップダウンターミナルのキーバインドが被っている

### ISSUE THREAD

**Issue by wentz-pie** [FascodeNet/alterlinux#251]
vscodeで定義に移動(F12)を押すと、xfceドロップダウンターミナルが開きます。
皆さんどうしてるんでしょうか?

vscodeのF12は、結構使うので、xfceドロップダウンターミナルのキーバインドの変更したいと思います。
方法があれば、ご教授お願いします。

64bit版 xfceエディション 日本語版を使用しています。

**Comment by Hayao0819** [comment]
1. 「設定マネージャー」→「キーボード」と進んでください
2. コマンドが「`xfce4-terminal --drop-down`」ショートカットが「`F12`」という項目を見つけ出します
3. 右側の「F12」をダブルクリックし、キーボードショートカットを変更してください
4. もしくは下の「Remove」ボタンを押して削除してください
5. VScodeを起動してF12キーが競合していないことを確認してください

F12キーは特に理由もなく開発者が設定しただけのキーですので、もし何か具体的な案があったら教えていただければ幸いです。

**Comment by wentz-pie** [comment]
返答ありがとうございます。

ご案内いただいた通り、設定できました。
自宅や職場でvscodeを使うこともあって、デフォルトキーバインドを好んでいます。
開発でキーバインドが馴染んているかどうかで、
今回は、xfce-terminalをShift + Ctrl + %に変更しました。

余談ですが、
drop down terminalが、Plankの様に常駐しているものと、勘違いしていました。
お恥ずかしい。勉強になりました。
