### ISSUE TITLE
Pacmanの更新によってTotalDownloadの警告が出る

### ISSUE THREAD

**Issue by wentz-pie** [FascodeNet/alterlinux#257]
yayを実行すると、「設定ファイル /etc/pacman.conf, 40 行: セクション 'TotalDownload' のディレクティブ 'options' が実行できません。」という警告が表示されます。
yayの表示の問題なのかと思っていますが、解消できる方法があれば、教えていただけると助かります。

![スクリーンショット 2021-06-25 085637](https://user-images.githubusercontent.com/53452986/123346607-a8924880-d593-11eb-88df-7a53c63b92ed.png)

この現象がでる元となる異常がありました。
2021/6/24に3か月ほど放置したalter linuxにyayを実行し、大量のアップデートをしたところ、エラーで失敗しました。
以降yayは、「yay: error while loading shared libraries: libalpm.so.12: cannot open shared object file: No such file or directory」のエラーでアップデートできなくなる。

次の手順を行ったところ、アップデートできるようにはなりました。
1. pamac-managerも起動しなくなった。
2. yayアンインストール
3. yay-binインストール
4. pamac-aurをアンインストール 
5. yay実行 成功
6. pamac-aurインストール
7. pamac-managerも起動するようになる

yayは成功するようになったものの、「設定ファイル /etc/pacman.conf...」の警告が出るようになりました。

カーネル Linux 5.12.12-zen1-1-zen

**Comment by wentz-pie** [comment]
エラーと処置が違っていたので修正しました。

**Comment by Hayao0819** [comment]
次のコマンドの実行結果を教えてください。 `cat /etc/pacman.d/mirrorlist-alter`

また、`TotalDownload`についてはPacmanが更新されたことによる機能及び仕様の変更があったためです。
以下のコマンドを実行して修正できると思います。

```bash
sudo sed -i "s|^TotalDownload||g" `/etc/pacman.conf`
```

**Comment by wentz-pie** [comment]
お忙しいところ、返信感謝しています。

実行結果です。
`cat /etc/pacman.d/mirrorlist-alter`
![スクリーンショット 2021-06-28 084440](https://user-images.githubusercontent.com/53452986/123563011-2a30e300-d7ed-11eb-8158-9afcdcccdf1b.png)

TotalDownloadの件は、教えていただいたコマンドで、回復しました。
ありがとうございます。

**Comment by Hayao0819** [comment]
下2つの`# YamaD`から始まる行の下を`Server`をコメントアウトしてください

**Comment by wentz-pie** [comment]
分かりました。
コメントアウトしておきました。
