### ISSUE TITLE
パッケージアップデーターでパッケージのアップデートができない

### ISSUE THREAD

**Issue by kagirohi** [FascodeNet/alterlinux#259]
内容
タイトルの通り、「パッケージアップデータ」アプリケーションでのパッケージのアップデートができず、エラーが表示されます。
archwikiでパッケージをアップデートするためのコマンド `pacman -Syu`を調べて、そのコマンドを実行すると、アップデートは完了しました。
aptコマンドでもパッケージのインストールは可能でした。

ですが、その後も「パッケージアップデータ」がエラーを出します。
Linuxの初心者で、特にarchLinux系のディストロは、これがはじめてです。ご教示お願いします。

環境
VirtualBox上の仮想PC（ネットワーク接続はNAT）
メモリ:4GB
プロセッサ:intel core i5 6500 2core
ゲストOS:alterLinux20210715 32bit版 xfceデスクトップ環境

![VirtualBox_alterlInux_packageUpdater2](https://user-images.githubusercontent.com/57948679/126069874-41ab2f03-ea05-4aa3-a44a-a88398e1f32e.png)

**Comment by kokkiemouse** [comment]
コンソールに次のコマンドを入れて結果をスクリーンショットで送ってもらえますか？
pkcon refresh
pkcon update

**Comment by kagirohi** [comment]
![VirtualBox_alterlInux_pkcon](https://user-images.githubusercontent.com/57948679/126158957-fa8dbae7-f78b-4b33-8f81-209ec477f473.jpg)
上の画像のようになりました。

**Comment by kokkiemouse** [comment]
PackageKitではなくpamacの問題のようですね....

**Comment by Hayao0819** [comment]
以下のブログの記事の2つ目を実行してみてください。

https://blog.fascode.net/2021/07/20/alterlinux-update-failed/

**Comment by Hayao0819** [comment]
32bitなのでpamacはインストールされていないです。`gnome-packagekit`です。
