### ISSUE TITLE
PCE-AC88使用時にWifiに接続できない問題

### ISSUE THREAD

**Issue by sarukiti** [FascodeNet/alterlinux#26]
PCE-AC88使用時に発生しました
他のWifi子機でもはっせいするかはわからないです

**Comment by Hayao0819** [comment]
[こちら](https://ubuntuforums.org/showthread.php?t=2337200&p=13618497#post13618497)を参考にして下さい。
AlterLinuxでは特定のハードウェアへの対応を行うといったことはしません。
また、この問題はAlterLinuxではなくArchLinuxでの問題です。

**Comment by sarukiti** [comment]
それもそうですね > 特定のハード

**Comment by Hayao0819** [comment]
一部のマシンに最適化しちゃうのはよくないので...
すみませんm(_ _)m
