### ISSUE TITLE
pacmanコマンドでパッケージデータベースが開けない

### ISSUE THREAD

**Issue by DaiGuard** [FascodeNet/alterlinux#260]
**Describe the bug**

Alter Linuxをインストールした直後、`pacman`コマンドを使って
`samba`をインストールしようとした際、以下のエラーが発生した

**To Reproduce**

```bash
$ sudo pacman -S samba
エラー: ファイル /var/lib/pacman/sync/core.db を開けませんでした: Unrecognized archive format
エラー: ファイル /var/lib/pacman/sync/extra.db を開けませんでした: Unrecognized archive format
エラー: ファイル /var/lib/pacman/sync/community.db を開けませんでした: Unrecognized archive format
エラー: ファイル /var/lib/pacman/sync/multilib.db を開けませんでした: Unrecognized archive format
エラー: 対象が見つかりませんでした: samba
```

**Desktop (please complete the following information):**
 - OS: Alter Linux
 - Linux version 5.12.15.15-zen1-1-zen
 - App: pacman v6.0.0

**Comment by naoko1010hh** [comment]
https://blog.fascode.net/2021/07/20/alterlinux-update-failed/
この方法では解決しませんでしょうか？

**Comment by DaiGuard** [comment]
@naoko1010hh 
ありがとうございます
解決しました
