### ISSUE TITLE
Snap経由のソフトウェアで日本語入力ができない

### ISSUE THREAD

**Issue by tubuanha** [FascodeNet/alterlinux#262]
**Describe the bug**
Visual Studio Codeで日本語入力ができません。
他のソフトウェア(DiscordやChrome)では正常に入力できます。
Mozcの仮想キーボードも使用して入力を試みましたが、入力できませんでした。

**To Reproduce**
1. VSCodeを開きます。
2. 日本語入力モードで入力します。

**Expected behavior**
正常に日本語入力ができる

**Desktop (please complete the following information):**
 - OS: Alter linux KDE Plasma edition (最新バージョン)
 - VSCode: 1.58.2

**Comment by Hayao0819** [comment]
インストールしたパッケージの名前を教えてください
（VScodeにはいくつかのバリエーションがあります）

**Comment by tubuanha** [comment]
[こちら](https://snapcraft.io/code)のsnapcraftのものです。

**Comment by Hayao0819** [comment]
snap経由だと問題が発生すると聞いたことがあります
snap版ではなく`visual-studio-code-bin`をインストールしてみてください

```bash
yay -S visual-studio-code-bin -a --noconfirm 
```

**Comment by Hayao0819** [comment]
https://askubuntu.com/questions/1241667/japanese-input-ubuntu-18-04-applications-installed-via-snap

こちらの情報によると以下のコマンドで解決できるそうです（動作は未確認です）

```bash
gsettings set org.gnome.desktop.input-sources per-window true
```

**Comment by tubuanha** [comment]
ありがとうございます！
yayでインストールして解決しました。
