### ISSUE TITLE
インストール時にネットワークに接続されない / Not Connected to Networks on installation

### ISSUE THREAD

**Issue by Ljohske** [FascodeNet/alterlinux#265]
これはさほど大きな問題でもないかもしれませんが、要望を兼ねて、また初心者で Alter Linux のインストールに挑戦する方のためにここに書いておこうと思います。

最初、「Alter Linux をインストールする」というデスクトップアイコンをクリックしても、「ネットワークに接続されていません」という警告が出てしまうはずです。この場合、ターミナルから 
systemctl start NetworkManager.service
と打ち込めばタスクバーや設定の項目からネットワークの設定ができるようになるはずです。

できれば, このネットワークのサービスをコマンドで起動しなければそもそもインターネットに接続できない、という問題をインストールスクリプトなどの変更等で解決していただけませんか？

I am not sure whether I should open a issue here on this, but I think this might be helpful if somebody relatively new to linux wants to install Alter Linux. (with *little* intention to request some fixes to the mishaps)

If you try to install Alter Linux (e.g. from a Bootable Live USB memory), you might find the “Install AlterLinux” tool warning you of ‘not being connected’ to the internet, even though you cannot set them manually from user interface graphically.

In such a case you just need to run the following command on the terminal:

$ systemctl start NetworkManager.service

Then the graphical Network manager should start running.

I will certainly appreciate if this could be fixed somehow, since it would trouble some of the new user not familiarised with unix/linux commands and configurations.

**Comment by naoko1010hh** [comment]
Issuesありがとうございます。
ソースコード上では修正されております。次のビルドで修正されると思われます。

Thanks for the Issues.
The problem has been fixed in the source code. It is expected to be fixed in the next build.

https://github.com/FascodeNet/alterlinux/commit/c594fc9e803ca08c8520eb7f65fe6608f7711f56

**Comment by Hayao0819** [comment]
Issueのトップに表示させれいただきます。
