### ISSUE TITLE
ロック画面からの復帰挙動が不安定な場合がある

### ISSUE THREAD

**Issue by win-chanma** [FascodeNet/alterlinux#266]
はじめまして。
下記現状が生じております。
解決策などございましたら、ご教示願いたいです。

【現象】
1.スクリーンロックショートカットで画面ロック（mod+Ese)
2.ログイン画面（ようこそ）表示
3.パスワードを入力してEnter
4.画面が暗転し、再度ログイン画面が表示される
5.パスワードを入力してEnter
6.ロック解除された状態で復帰

【発生条件】
2021/08/29現在、1/5で発生
※2021/08/20の段階では3/3で発生していた現象

長く放置していると発生しやすいので省電力周りが関係しているかも

【利用しているAlterLinux】
alterlinux-i3-ja-2021.07.18-51dcbab60-x86_64

【利用しているマシン】
MacBook Pro (13-inch, Mid 2012)
メモリ16GBへ増設済
https://support.apple.com/kb/sp649?locale=ja_JP

**Comment by Hayao0819** [comment]
電源管理のTLPを無効化してみてください。
`sudo systemclt disable tlp`

**Comment by win-chanma** [comment]
@Hayao0819 

回答ありがとうございます。
上記コマンドでTLP無効化した後、Issueの現象は発生しませんでした。
(10/10で正常なロック解除)

大変助かりました。ありがとうございます。
