### ISSUE TITLE
操作ミスで大きなBEEP音がなってしまう問題

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#27]
2020/03/25あるいは2020/03/26ビルドにてちょっとしたGUIの操作ミスで大きなBEEP音がなってしまう

東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
どのアプリケーションでどういったタイミングで鳴るかをわかる範囲で良いので詳しく教えてほしいです。

**Comment by naoko1010hh** [comment]
xfce4-popup-whiskermenu や　設定マネージャーなどxfce4系のソフトウェアでおきます。
どういうタイミングでなるかといいますと
キーボードでこれ以上動かない方向に移動したりした際に警告のような形でなります。

**Comment by Hayao0819** [comment]
修正しました
