### ISSUE TITLE
ブートローダーがインストールできません

### ISSUE THREAD

**Issue by SuperSandyman** [FascodeNet/alterlinux#273]
![16379181196726644506581199230193](https://user-images.githubusercontent.com/66544945/143556618-749a9150-ba69-4e32-ab89-de5a2ef30e0b.jpg)
上の写真のようなエラーがインストール中に出てきます。2回ほどやり直しましたが、エラーが出ました。64bitのxfceを使いました。パソコンは、Dynabook N51/25Mです。特に改造などはしてません。

**Comment by naoko1010hh** [comment]
issuesありがとうございます。
使用しているバージョンやISOファイル名を記述してください。

**Comment by naoko1010hh** [comment]
https://dynabook.com/pc/catalog/dynabook/140616n51/spec.htm

**Comment by SuperSandyman** [comment]
ISOファイルはこちらを使っています。
alterlinux-xfce-ja-2021.09.20-d0fb75b7f-x86_64.iso

**Comment by naoko1010hh** [comment]
ISOファイルの記述ありがとうございます。

同じノートパソコンが用意できないため
仮想環境及び別な型番の実機にて記載いただいたISOファイルで
検証行ったところ問題が確認できませんでした。

同じ報告がなければDynabook N51/25M固有の問題が考えられます。

**Comment by SuperSandyman** [comment]
いろいろとありがとうございました。まだ諦めきれないのでエラーメッセージの解読を頑張ってみます！

**Comment by SuperSandyman** [comment]
あの後、いろいろやってみました。その結果、UEFIでMBRでパーティショニングをするとインストール成功しました！
