### ISSUE TITLE
AlterLinuxの国際化対応（i18n）について

### ISSUE THREAD

**Issue by 4ioskd** [FascodeNet/alterlinux#274]
バグレポートではありませんが...
AlterLinux自体もそうですが、公式サイトを日本語と英語だけでなく、今後様々な言語に国際化対応（i18n)する考えはありますでしょうか。例えば、メジャーなLinuxディストリビューションで言えば、Debian( https://www.debian.org/ )は国際化対応されており、様々な言語でそのディストリビューションや公式サイトを利用することができます。

**Comment by Hayao0819** [comment]
現在、公式サイトやドキュメント含め大半は数名の学生のボランティアが開発しています。
開発メンバーの大半が現在受験期を迎えているので開発の停滞気味なのが現状です。
OSDNのアクセス解析によると大半が日本語もしくは英語圏からのアクセスなので、今の所対応言語を増やす予定はありません。
また、サーバの負荷やビルドの負担の関係上Alter Linuxの対応言語そのものを増やすことも難しいのでそういった意味でも公式サイトを他の言語に対応させるのはあまり意味がないと考えています。

**Comment by 4ioskd** [comment]
なるほど、分かりました。
受験勉強は大切なことなので、開発との両立は大変でしょうが、頑張ってください。
対応言語については受験勉強もありますし、現在のところはその必要性が無さそうですね。将来的に日本語または英語圏以外のユーザーが徐々に増えてくることがあれば、その時はそのための準備をすれば良さそうですね。
以上です。陰ながら応援しております。

**Comment by Hayao0819** [comment]
ありがとうございます。
