### ISSUE TITLE
最新のアップデートをかけるとfirefoxが起動しなくなる件

### ISSUE THREAD

**Issue by kagirohi** [FascodeNet/alterlinux#275]
**バグの概要**

今日時点(2021/12/17)で、sudo pacman -Syuでパッケージのアップデートをかけたあとに,firefoxを起動したら、エラーが出て動作しない。

**手続き**

1. 端末で $ `sudo pacman -Syu`　を実行
2. アップデータ中にエラーがいくつか表示される。
3. アップデート終了後に、firefoxを起動させようとしてもエラーを吐く。
![VirtualBox_alter_17_12_2021_20_45_02](https://user-images.githubusercontent.com/57948679/146541078-c96c9212-af49-4738-8b2f-87f870172a04.png)

4. firefoxをアンインストールやってからfirefoxに関係してそうなファイルを削除してからの再インストールでも不可。
`sudo pacman -Rn firefox`
「firefox」で検索にかけた後、関係ありそうな２つのフォルダと一つのファイルを削除
`sudo find / -name "firefox" `
`rm -r $HOME/.cache/mozilla/firefox/ $HOME/.mozilla/firefox/`
`sudo rm /usr/share/bash-completion/completion/firefox`
インストール
`sudo pacman -S firefox `
`firefox`
同上のエラー
**きになること**
アップデート中にも警告が出た。一応、終了はできた。
firefoxのセーフモードでも起動不可。
`firefox --safe-mode`
**スクショ**
アップデート中の警告やエラー
![VirtualBox_alter_17_12_2021_20_56_41](https://user-images.githubusercontent.com/57948679/146541572-b7960138-537b-4d3f-b05a-2575f06aba40.png)
![VirtualBox_alter_17_12_2021_20_57_05](https://user-images.githubusercontent.com/57948679/146541575-a1af0de6-1d8d-4c91-b5a5-8f0fab870cf0.png)
![VirtualBox_alter_17_12_2021_20_57_22](https://user-images.githubusercontent.com/57948679/146541579-09dc8442-70ad-46c5-ae24-143f77b82aca.png)

**環境**
 - OS: AlterLinux i686 32bit xfceデスクトップ
 -　マシン :仮想マシン VirtualBox CPU Intel i5-6500 　メモリ 3072MB
VirtualBox ver:6.1

**Comment by Hayao0819** [comment]
こちらでも同様の問題を確認しました。
Alter LinuxではなくArch Linux 32の問題なので上流へ報告させていただきます。

**Comment by kagirohi** [comment]
了解です。
迅速な対応、ありがとうございます。

**Comment by Hayao0819** [comment]
![image](https://user-images.githubusercontent.com/32128205/146548641-b9ca69ae-2628-41d9-b84c-42482d5ea4b4.png)

**Comment by Hayao0819** [comment]
上流に報告しました。対応をしばらくお待ちください。
https://bbs.archlinux32.org/viewtopic.php?pid=8706
