### ISSUE TITLE
パッケージの更新に失敗する。 The requested URL returned error: 404  Maximum file size exceeded

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#277]
状況↓

少し前からpipewire関連のパッケージの更新に失敗するケースはありましたが、
[Twitter](https://twitter.com/aozikosyoten/status/1490597456848904192)にて報告が上がっており仮想環境を使用し改めて検証を行ったところ、
Alter Linux関連のリポジトリでエラーが発生しているようです。

行ったことは
まず下記のコマンドでpipewire関連のエラーを回避します。
yay -R pipewire-jack-dropin pipewire-jack
yay -Syyu 
yay -S pipewire-jack

次に下記のコマンドで改めて更新をかけようとするとエラーが発生します。
yay -Syu

エラーの内容はログを貼りますのでそちらをご覧いただけますと幸いです。

[gistfile1.txt](https://github.com/FascodeNet/alterlinux/files/8014587/gistfile1.txt)

![image](https://user-images.githubusercontent.com/50263013/152771631-dc673ea6-c716-4479-a539-926ce0201c19.png)

使用したISO↓

https://storage.dyama.net/alter/release-candidate/release/2021.12.01/alterlinux-xfce-ja-2021.12.01-aea176594-x86_64.iso

仮想環境↓

![image](https://user-images.githubusercontent.com/50263013/152771558-c82aba8b-da81-4368-ad7c-f526a2a1559f.png)

**Comment by Hayao0819** [comment]
以下のリポジトリへの修正で、少なくとも最新のイメージファイルで動作を確認しました。

https://twitter.com/Hayao0819/status/1490676207301849091
https://twitter.com/Hayao0819/status/1490695968240836608

- [データベースへの署名を無効化しました](https://github.com/FascodeNet/alterlinux-repo/commit/5835350ed69516c1bcd6407ddc9d6e5db9c92f94)
- [同じパッケージを複数回ビルドしないようにしました](https://github.com/FascodeNet/alterlinux-repo/commit/6657cd42a85d19a1eb65e1258c6536db18b19c81)
- [カスタマイズされたmakepkg.confを使うようにしました](https://github.com/FascodeNet/alterlinux-repo/commit/b95a2803db13e1b0dd2a3cd6cf798e4f3b04c5a6)
- [スキップリストを正常に取得できないバグを修正しました](https://github.com/FascodeNet/alterlinux-repo/commit/4b16bbb7edc755ea2f576e9a5161e83404d3dbe7)

**Comment by naoko1010hh** [comment]
昨日検証した環境のスナップショットで再度更新を行ったところ成功しました。
しっかりと修正されているようです。

**Comment by naoko1010hh** [comment]
一部の環境では下記の方法を行う必要があるようです

https://twitter.com/nemu1113m/status/1490884018652717062?s=20&t=hrwq2rWPV0FsHSl1uOe1aw
