### ISSUE TITLE
i3wm alter-system-menu　コマンドがインストールされていない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#280]
Discordにてi3wmのmod+Bの設定が呼び出せないとご報告がありライブ環境にてショートカットを実行したところalter-system-menuというコマンドが見つからないようです。
取り急ぎissuesを立てたためログ提出はありませんが必要があれば順次追加します。

![VirtualBox_alter cinnamon mig kensyou_23_02_2022_19_35_54](https://user-images.githubusercontent.com/50263013/155303517-035b5804-be56-4211-b69b-5c7f9ecd6372.png)

Discordの会話↓
https://discordapp.com/channels/642666144288735243/642671517137633285/945991012835287073

使用したISO↓
https://storage.dyama.net/alter/release-candidate/release/2022.02.08/alterlinux-i3-ja-2022.02.08-967ac61a4-x86_64.iso

仮想環境↓
![image](https://user-images.githubusercontent.com/50263013/155303045-48efd514-be9a-44fe-bc3a-d04a3c958eba.png)

**Comment by watasuke102** [comment]
コマンドはインストールされてますが実行権限がないです

`sudo chmod 755 /usr/bin/alter-system-menu` で解決します

**Comment by naoko1010hh** [comment]
Close後にコメント失礼。
commitハッシュ記述または修正されてからCloseしたほうが良いと思います。

**Comment by watasuke102** [comment]
それはそう

**Comment by adeno921** [comment]
上記のコマンドを実行したところ直りました
ありがとうございます。
環境はThinkPad E560 でisoファイルは消してしまいましたが、2/10に落としたものです

**Comment by watasuke102** [comment]
次回のリリース時には修正されていると思います
