### ISSUE TITLE
mozc_tool 起動のショートカットが ~/.config/i3/config で定義されていないのが初心者に優しくない

### ISSUE THREAD

**Issue by mitsugu** [FascodeNet/alterlinux#281]
**バグの概要**
mozc_tool 起動のショートカットが ~/.config/i3/config で定義されていないのが初心者に優しくない

**対象**
- AlterLinux I3 Japanese 64bit
- AlterLinux I3 Global 64bit

**提案**
デフォルトで ~/config/i3/config に mozc_tool を起動するショートカットを加える。

例)
> bindsym $mod+m exec --no-startup-id /usr/lib/mozc/mozc_tool --mode=config_dialog

**Comment by mitsugu** [comment]
/home/mitsugu/Work/alterlinux/channels/i3/airootfs.any/root/customize_airootfs_i3.sh
に
> # add shortcut for '/usr/lib/mozc/mozc_tool --mode=config_dialog'
> echo 'bindsym $mod+m exec --no-startup-id /usr/lib/mozc/mozc_tool --mode=config_dialog' >> "/home/${username}/.config/i3/config"
とか追加すればいいのかな？

**Comment by watasuke102** [comment]
（もし追加する場合は、customize_airootfs_i3.shではなく直接airootfs.any/etc/skel/.config/i3/configに追記します）

これは個人的な意見ですが、mozc_toolは常用ツールであるとは思っていません。
i3のコンフィグファイルに起動用のキーバインドを登録しているソフトは、ターミナルやスクリーンショットツール等、起動したいと思う場面が比較的多いものと考えています。個人の経験上専用キーバインドを用意してまでmozc_toolを複数回起動するケースを想像できなかったため、追加する予定はありません。

一旦閉じますが、もしデフォルトで追加してほしい・追加されなければ困る等の声が一定数集まった場合は再度検討する予定です。
