### ISSUE TITLE
WIFIの自動接続がされない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#29]
alterlinux β1の使用者からの報告です。

起動時wifiに自動で接続されないです。手動でwifiを選択するとつながります。機種はdynabook R732です。
https://twitter.com/hyuoou/status/1246752262405251072
とのことです。

こちらでも検証したとこ下記の環境でも同じことがおきました
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
Wi-Fiの自動接続はサポートしていません。
他のLinuxディストリビューションではできましたか？

**Comment by naoko1010hh** [comment]
Ubuntuやzorin　osやSereneLinuxなどでは自動で繋がりました

**Comment by Hayao0819** [comment]
手動だと接続できますか？

**Comment by hyuoou** [comment]
コメント失礼します。wifiが自動接続できないとツイートした者です。
私の環境で確認したところSereneLinux、Manjaro共に自動で認識してくれました。
一応wifiモジュールの名前を書いておきます。
Qualcomm Atheros AR93xx Wireless Network Adapter

**Comment by Hayao0819** [comment]
その機種以外のマシンで、自動再接続ができたかどうかを確認してください
私の環境でも確認してみます
これは機種固有の問題なのかソフトウェア側の問題なのかを切り分けるためです

**Comment by hyuoou** [comment]
私が普段使っているメインPCにAlterLinuxをインストールしました。私の環境では2台とも同様の症状が発生しました。

**Comment by mk-linux419** [comment]
横から失礼します。
"全てのユーザーのアクセスを許可する"という項目がwifi設定のところにあると思います。
それを有効にすれば多分治ると思います。

**Comment by naoko1010hh** [comment]
全ユーザーがこのネットワークに接続可能とするになってるのですがうまく行きませんね。

**Comment by hyuoou** [comment]
コメント失礼します。
私はLinuxについて詳しいわけではないのでよくわかりませんが
NetworkManagerアプレットのバージョンが
AlterLinuxでは1.16.0　Manjaroでは1.8.24になっていたのですが
関係あるのでしょうか

**Comment by Hayao0819** [comment]
AlterLinuxは大部分のソフトウェアをArchLinuxと共有しています
ArchLinuxのリポジトリが更新されないとこちらも更新されません
Manjaroで正常に自動接続ができたとのことですが、systemdのバージョンを教えていただけないでしょうか。

**Comment by hyuoou** [comment]
sudo journalctl --version
コマンドはこれでよいのでしょうか
systemd 244 (244.4-1-manjaro)　と出てきました

**Comment by Hayao0819** [comment]
Manjaro...？

**Comment by Hayao0819** [comment]
私のノートPCでこの問題を確認しました。
引き続き調査を進めていく予定です

**Comment by Hayao0819** [comment]
情報が見つかりました。
以下の方法で自動接続を行うことが可能です。

[ArchWiki Network Manager ログイン時に自動的に接続する](https://0e0.pw/tvoD)

**Comment by hyuoou** [comment]
自動接続ができました。ありがとうございます。

**Comment by Hayao0819** [comment]
[こちら](https://0e0.pw/18fv)に日本語版AlterLinuxでの解決方法をまとめました
今後はそちらをご覧ください
