### ISSUE TITLE
日本語ファイルが含まれるzipファイルを回答すると文字化けする問題

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#30]
環境変数の設定がされていないため日本語が含まれるzipファイルの解凍が文字化けする。

![https___s 0u0 biz_api_v4_image_url=https%3A%2F%2Fi gyazo com%2F5f205bfa9e51901c8faf0fffe47643c1](https://user-images.githubusercontent.com/50263013/78547090-7505ba00-7839-11ea-9cc6-9bb0f4128f56.png)

2020/04/05ビルド
xfce channel
jp mode enable

コミットハッシュは```206b124f50ecb7b1c8c19cd214b1b3d64e91b721```

環境
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
## 原因
`.xinitrc`に書かれている変数が設定されていません
```
export ZIPINFOOPT=-OCP932
export UNZIPOPT=-OCP932
```

**Comment by Hayao0819** [comment]
CLI上では修正されましたが、GUIでは修正は難しいようです。
