### ISSUE TITLE
統合グラフィックス(NVIDIA/Intel)搭載PCでバッテリー駆動だとXやコンソールがフリーズする

### ISSUE THREAD

**Issue by Fialka144** [FascodeNet/alterlinux#32]
AlterLinuxのLiveUSBをバッテリー駆動状態で起動すると,起動ログが一通り流れたあと画面が暗転したまま動かなくなってしまいます(ctrl+alt+delやctrl+alt+backspaceでの強制終了も出来ない状態です)
バッテリ駆動ではなくACアダプタに接続した状態で起動すればこの現象は回避できます
PC:HP Pavilion-Power laptop 15
CPU:Intel Core i7 7700HQ
RAM:16GB
GPU:GTX-1050/Intel HD 630
環境依存の可能性がありますが,検証可能な他のPCを所持していないため,他環境での検証は出来ていません

**Comment by Hayao0819** [comment]
ブートスプラッシュを使用しない項目で起動し、最後のログを教えてほしいです
また、バッテリーの寿命なども確認してみて下さい

**Comment by Supershell345** [comment]
バッテリーの寿命については,3月に交換したばかりなので問題は無いです
起動中の画面については,ブートスプラッシュが表示されることなく起動ログが流れ,

(= =) Using system config directory "/usr/share/X11/xorg.conf.d"
_

と表示されたのを最後に画面が暗転し,
バッテリ駆動だとそのまま止まってしまいますが電源使用時だと正常にデスクトップ画面が表示される,といった状態です

**Comment by Hayao0819** [comment]
となると起動そのものは正常に行えているようです。
Ctrl + Alt + F2で別のターミナルが起動するか試してみてください。

**Comment by Supershell345** [comment]
起動ログ画面の状態であればCtrl+Alt+F2を受け付けてプロンプトが点滅しますが,一切の入力を受け付けなくなってしまいます(Ctrl+Alt+Backspaceのリセットも使えない)
また,画面が完全に暗転した状態では別のターミナルを起動することができず,Ctrl+Alt+Backspaceも使えません

**Comment by Hayao0819** [comment]
画面出力はCPUとGPUのどちらを使用しているかわかりますか？

**Comment by Supershell345** [comment]
Windowsから設定を見るとIntelのグラフィックプロセッサから出力されていることになっており,恐らくAlterLinuxも同様の仕様と思われます

**Comment by Hayao0819** [comment]
わかりました
原因を探ってみます

**Comment by Supershell345** [comment]
補足です
HDDにインストールが完了したAlterLinuxをバッテリー駆動で起動させたところ,ディスプレイマネージャでパスワードを入力することができますが,ログインボタンを押してしばらくすると画面が暗転し,マウスカーソルが動かなくなります(キーボード含め一切の操作を受け付けなくなる)

**Comment by Hayao0819** [comment]
TLPを削除してみて下さい
```
yay -Rsnc tlp
sudo systemctl disable tlp.service
```
その後、再起動してみて下さい

**Comment by Supershell345** [comment]
駄目でした...TLPを削除して無効化してからAC電源を繋がずにバッテリーから起動してみましたが,ログインするとフリーズしたり,仮想コンソールを出すとフリーズする現象は改善できませんでした

**Comment by Supershell345** [comment]
それに恐らくTLPを無効にした影響で電源接続時でも同様の現象が起こるようになってしまいました...

**Comment by Hayao0819** [comment]
とりあえずLiveUSBで起動し、パーティションをchroot、tlpを再度インストールして`sudo systemctl disable tlp.service`を実行してTLPを再度有効化してください
TLPの設定を変更することで改善する可能性が有ります

**Comment by Supershell345** [comment]
TLPの再度有効化には成功し,電源接続時に正常な起動ができるようになりました
TLPの設定をどのように変更すれば,AC接続時と同じ挙動でバッテリー起動ができるようになりますか?

**Comment by Supershell345** [comment]
TLPの再度有効化には成功し,電源接続時に正常な起動ができるようになりました
TLPの設定をどのように変更すれば,AC接続時と同じ挙動でバッテリー起動ができるようになりますか?

**Comment by Hayao0819** [comment]
まだ原因が不明なので解決方法もわかっていません
あくまでTLPに解決の糸口があると考えています
設定に「TLPUI」というTLPをGUIで設定を変更できるのでそこでいろいろを変えてみて下さい

**Comment by Cipherbit0424** [comment]
他のディストリビューションと比較するために,
同じArch系でインストール方法が似ているManjaroLinuxを同じ環境にインストールしてみました(今回インストールしたのはGnome Edition)
インストールisoの起動時に読み込むドライバー(インストールにも適用される)がfree(nouveau)とnon free(プロプライエタリ)の両方があったので試しています
結果としては,どちらもバッテリ駆動で正常に起動しました
何かの参考になるかもしれないので一応報告しておきます

**Comment by Hayao0819** [comment]
Manjaroはソフトウェアやドライバの検知などが異なるため、（MHWDと呼ばれる独自のドライバ検知ツールを使用している）ArcoLinuxなどの純粋なArchLinux派生OSで試していただけないでしょうか？
純粋というのは、リポジトリをArchと共有しているディストリビューションのことです。
こちらの環境ではバッテリー駆動でも正常に動作したので...

**Comment by Hayao0819** [comment]
最新のBeta3.1で様々なドライバが追加されて、GUIの起動方法も改善されました
最新版で正常に起動するかどうか確認してみて下さい

**Comment by Fialka144** [comment]
最新のBeta3.1のisoを焼いたUSBのバッテリー駆動での起動と,それを用いてインストールしたAlter Linuxのバッテリーでの起動を試しました.
後者の方はデスクトップが表示されるまで時間がかかりましたが,どちらも正常に使えるようになったことを確認しました.

**Comment by Hayao0819** [comment]
よかったです
