### ISSUE TITLE
要望：ログイン画面の時計について

### ISSUE THREAD

**Issue by scarlet-Chun-DH** [FascodeNet/alterlinux#34]
バグ報告というよりは開発者への要望(もし自力でできそうなら自分でカスタマイズする)といったものですが、Alter Linuxデフォルトのログイン画面(webkit2)の時計を24時間式に変更することはできますか？ どのソースファイルに手を加えればよいか教えていただければ幸いです。また、今後の利用者の方にも便利にしていただけるように更新していただけるとありがたいです。

**Comment by Hayao0819** [comment]
時計を右クリックし、表示形式の部分で`%I`を`%H`に変えてみて下さい

**Comment by scarlet-Chun-DH** [comment]
試してみましたが、私の環境の場合右クリックが反応しません。

**Comment by scarlet-Chun-DH** [comment]
大変お騒がせいたしましたが自己解決に至りました。
/use/share/lightdm-webkit/themes/alter/js/splash` screen.jsの時刻設定の部分をhからHHにして”A”を消せば24時間表記になります。

**Comment by Hayao0819** [comment]
すみません見落としていました。デスクトップのことじゃなくてログイン画面だったんですね。

**Comment by Hayao0819** [comment]
12時間表記と24時間表記は結構派閥が分かれているのでまだどっちにするかなどは検討中なんです

**Comment by scarlet-Chun-DH** [comment]
そうですか。了解いたしました。
