### ISSUE TITLE
nssアップデートに関する不具合についての報告

### ISSUE THREAD

**Issue by scarlet-Chun-DH** [FascodeNet/alterlinux#37]
こんばんは。pamacを用いてアップデートをしようとしたところ、以下のような不具合が出ました。
> 衝突しているファイル:
> nss: /usr/lib/p11-kit-trust.so は既にファイルシステムに存在します

解決していただけないでしょうか。

**Comment by Hayao0819** [comment]
原因は不明ですが以下の方法でエラーを強制的に修正することができます。
問題を調査してみましたが、AlterLinux固有の問題ではないと思われます。
おそらくそれはArchLinux（や更に上流）の問題です。

```bash
sudo pacman -Syy
sudo pacman -Syu --overwrite /usr/lib/p11-kit-trust.so
```

**Comment by scarlet-Chun-DH** [comment]
ありがとうございます。先程のコマンドに従ったところ順調にアップデートできました。

**Comment by Hayao0819** [comment]
すみませんその後、複数ヶ所から報告が上がりました。
おそらくArchLinuxの問題だとは思いますがAlterLinux側でも調査を進めてみます

**Comment by PC-FREEDOM** [comment]
参考になりました！

**Comment by Hayao0819** [comment]
これはArchLinuxの問題だったようですね。
[nss>=3.51.1-1 と lib32-nss>=3.51.1-1 への更新は対応作業が必要です](https://www.archlinux.jp/news/nss3511-1-and-lib32-nss3511-1-updates-require-manual-intervention/)

**Comment by PC-FREEDOM** [comment]
ありがとうございます！
