### ISSUE TITLE
wizard.sh の『圧縮の詳細を設定しますか？』 という質問が正常に動作しない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#39]
![4GV914gR](https://user-images.githubusercontent.com/50263013/79352956-6e7fec80-7f75-11ea-8db9-b7cbdcb7ad06.png)

ホストOSはAlterLinux

環境
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
修正しました
