### ISSUE TITLE
VBoxでXが自動的に起動しない

### ISSUE THREAD

**Issue by Hayao0819** [FascodeNet/alterlinux#41]
VirtualBox上でLXDE版のAlterLinuxを起動すると`startx`が実行されず、Zshが表示されます。
手動で`startx`を実行すればLXDEが表示されます。
また、手動で`./.zprofile`を実行しても正常にLXDEが表示されます。
Xfce版にある「VBoxでグラフィックコントローラをVBoxSVGAにしないと起動しない」という問題とは関係がないと思われます。

**Comment by watasuke102** [comment]
同様の不具合を確認しました。zshが表示され、startxで問題なく表示されます。

- ホストWindows10、VirtualBox6.0.20
- グラフィックスコントローラーはVMSVGA、VBoxVGAで確認
- 3Dアクセラレーション有効
- OSDN、Github、山D鯖のどこからダウンロードしても同様

**Comment by Hayao0819** [comment]
#44 との関連性は現在調査中

**Comment by Hayao0819** [comment]
おそらく上記のコミットで修正されました

**Comment by Hayao0819** [comment]
どうやら修正されていない？

**Comment by naoko1010hh** [comment]
LINEOpen CHATの方でルミさんからOsが起動しないとの報告がありましたのでgithubにも報告します。


実機環境
Core2 Quad
DDR2の2GB×2　

Lxde版のBETA２似て発生

発生当時のスクリーショット↓
![20200515120817](https://user-images.githubusercontent.com/50263013/82115401-6ea22080-979d-11ea-9c6f-3fbe41f583bf.jpg)


症状はshellがループするような感じで機動しない

**Comment by Hayao0819** [comment]
その問題は恐らくべつの問題なので新しくIssueを立てて下さい
おそらくこの問題は既に修正されています
その問題は別の問題です
