### ISSUE TITLE
パスワード無しでドライブをマウントできるようにする

### ISSUE THREAD

**Issue by sarukiti** [FascodeNet/alterlinux#42]
**概要**
いちいちパスワードを入れるのが非常に面倒だったので対応してください

**方法**
1. storageグループにユーザを追加
```usermod -aG storage [user-name]```
2. 10-enable-mount.rulesの作成
```nano /etc/polkit-1/rules.d/10-enable-mount.rules```
3. 下記をつくったファイルに追加
```polkit.addRule(function(action, subject) {
	if (action.id == "org.freedesktop.udisks2.filesystem-mount-system" && subject.isInGroup("storage")) {
	    return polkit.Result.YES;
	}
});
```
4. おわり

よろしくおねがいします

**Comment by Hayao0819** [comment]
http://nagamitsu1976.hatenadiary.jp/entry/2018/06/21/144455

**Comment by Hayao0819** [comment]
1a4c2a2160de97e7b22ff0b54cffebc2b4fbed59
