### ISSUE TITLE
startxを実行後もGUIが表示されない。

### ISSUE THREAD

**Issue by suzume-lab** [FascodeNet/alterlinux#43]
先程自分が持っている機種　
HP Mini 210-1021TU
にて beta2 xface版64bit(alterlinux-xfce-jp-2020.04.26-x86_64.iso)

をUSBから起動しようとしたのですがコマンドが表示され、
"startx"コマンドを実行後も下のリンクのような画面になりそれを数回繰り返しても同じ画面でGUIが表示されませんでした。
https://twitter.com/uminekosan31415/status/1255034031101505538?s=19

**Comment by Hayao0819** [comment]
#64 と似たような問題かもしれません
2eb66087b6a323fade467f16a9295936a5278801 でLightDMを経由する方法に変更されたのでBeta3でどうなるか確認してもらえないでしょうか

**Comment by suzume-lab** [comment]
わかりました!明日新規インストールをし、分かり次第報告します!

**Comment by suzume-lab** [comment]
先程Beta3　32bit版
(alterlinux-lxde2020.05.25-i686.iso)をUSBブートにて実行したところノーマルブートの状態ではAlterlinuxのロゴ表示後画面左上の隅に_の表示が出たままフリーズに似たような症状が発生しましたが、二個目のno splashにて起動してみたところ無事に起動し通常のGUI画面が表示されました。また、そこからインストールガイドに従ってインストールして再起動をしてみましたがインストール後の起動に関してはフリーズなどはなく通常起動、シャットダウンが確認できました。

改善ありがとうございますm(_ _)m

**Comment by Hayao0819** [comment]
ノーマルブートでのバグを 98f6ce248547dff8f931bd4b0ea04f194f95dc72 と 74ff432b67c6dbb11c4ca3f01551ad6f403c9813 で修正しました
