### ISSUE TITLE
一部の環境（Atom N450機種）でXが自動で起動しない

### ISSUE THREAD

**Issue by sunset0916** [FascodeNet/alterlinux#44]
機種名：Aspire One
CPU：Atom N450
RAM：DDR2 1GBx1
使用OS：Alter Xfce JP Beta2
この環境でX Window Systemが自動で起動せず。

**Comment by Hayao0819** [comment]
#41 との関連性は現在調査中

**Comment by Hayao0819** [comment]
@sunset0916 `startx`を実行するとどうなりますか？

**Comment by sunset0916** [comment]
startx実行でX起動したで

**Comment by Hayao0819** [comment]
サンガツ

**Comment by Hayao0819** [comment]
おそらく#41と重複しています

**Comment by ituki-108** [comment]
改善した模様です
Xeon-e3110 ram-6gb
alterlinux-xfce-2020.05.18-7cb7529-i686.iso
