### ISSUE TITLE
インストールがunpackfsやmkinitcpioで失敗する（開発途中のビルド）

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#45]
[サンセット](https://twitter.com/sunset09160306)さんよりmattermostに報告
ライブ起動は正常にできたけど、インストールに失敗した。
検証環境
SOTEC AFINA AG353
CPU：Pentium M 735 1C/1T 1.7GHz non-PAE i686Architecture
RAM：DDR 333MHz 1GB+512MB 1.5GB

エラー内容は

インストールに失敗
unsquash の設定が不正です。
ソースファイルシステム "/run/archiso/bootmnt/alter/x86_64/airrootfs.sfs" は存在しません

写真↓
![image](https://user-images.githubusercontent.com/50263013/80863039-57026c80-8cb4-11ea-9eba-87c0298232c8.png)

**Comment by Hayao0819** [comment]
210b2a87829e9744e5724bfcf58f3a6bbf4bc9ba で修正しました

**Comment by naoko1010hh** [comment]
クローズしていますが、また違うエラーが出たので追加報告します。

![VirtualBox_aa32_03_05_2020_15_57_16](https://user-images.githubusercontent.com/50263013/80907998-d2b4f580-8d56-11ea-81ba-60035d874f6a.png)


検証iso
https://山d.com/private/alterlinux-lxde-2020.05.03-i686.iso

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
このコマンドで修正できます
```bash
sudo sed -i s/cf/zen/g /usr/share/calamares/modules/unpackfs.conf
```

**Comment by naoko1010hh** [comment]
先程日本語isoに切り替えてしまったため日本語ISOですが上記のコマンドを実行しても同じようなエラーが出たので報告です。
![VirtualBox_aa32_03_05_2020_16_43_59](https://user-images.githubusercontent.com/50263013/80908760-84572500-8d5d-11ea-92eb-4e10c23f893c.png)


検証iso
https://山d.com/private/alterlinux-lxde-jp-2020.05.03-i686.iso

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
実行結果を教えてください
```bash
cat /usr/share/calamares/modules/unpackfs.conf
```

**Comment by naoko1010hh** [comment]
おまたせしました。こちらです。

![VirtualBox_aa32_03_05_2020_17_24_55](https://user-images.githubusercontent.com/50263013/80909454-74424400-8d63-11ea-9fc9-0cfde01ea3fe.png)

**Comment by Hayao0819** [comment]
上記のコマンドにミスが有ったため修正しました

**Comment by naoko1010hh** [comment]
了解しました。検証中です。

**Comment by naoko1010hh** [comment]
無事インストールできました解決ですね
