### ISSUE TITLE
AlterLinux i686でChromiumが起動しない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#46]
[サンセット](https://twitter.com/sunset09160306)さんよりmattermostにChromiumが起動してくれないからブラウジングできないと報告
ターミナルにて起動してみたらしいのでそのログをはっておきます。
おそらくlibicui18n.so.64がないからと思われる

写真↓
![image](https://user-images.githubusercontent.com/50263013/80863406-f9235400-8cb6-11ea-90c5-54d46e54a650.png)

検証環境
SOTEC AFINA AG353
CPU：Pentium M 735 1C/1T 1.7GHz non-PAE i686Architecture
RAM：DDR 333MHz 1GB+512MB 1.5GB

**Comment by Hayao0819** [comment]
調査したところ、おそらく以下のパッケージをインストールすれば解決すると思われます。
リポジトリへ反映する前にテストしていただけないでしょうか。

[ICU64 64.2-1](https://aur.archlinux.org/packages/icu64/)

**Comment by Hayao0819** [comment]
どうやら上流にてi686のChromiumが更新されていませんでした
よってデフォルトのブラウザをFirefoxに切り替えます

**Comment by naoko1010hh** [comment]
なるほど

**Comment by Hayao0819** [comment]
まだ問題は残っています #57
