### ISSUE TITLE
右下にWifi、音量調節などのアイコンが見えない

### ISSUE THREAD

**Issue by watasuke102** [FascodeNet/alterlinux#47]
システムトレイ右下に、設定などのアイコン（Wifi、音量調節、キーボード）が表示されず、仮想デスクトップと時刻のみが表示されています。
なお、一部環境では音量調節だけが表示されます。

- Alter Linux Lxde (Beta1)
- この現象を確認したもの
  - 音量調節アイコンのみ：(VirtualBox)[https://twitter.com/Watasuke102/status/1256733930595561472]、DynaBook t451/46DBS
  - なにも表示されない：(QEMU)[https://twitter.com/s32x8/status/1256729174422597632]、IN8i-15P1220-C-FEM

**Comment by watasuke102** [comment]
システムトレイが標準で配置されていないのが原因とのことです。
https://twitter.com/s32x8/status/1256749880615157760

**Comment by Hayao0819** [comment]
確認したところ日本語版のみの問題です。
