### ISSUE TITLE
GRUB entry is ArchLinux

### ISSUE THREAD

**Issue by lap1sid** [FascodeNet/alterlinux#5]
original-calamaresブランチビルド版で発生しました。
(全ブランチで発生する不具合のようです)

 It seems to be a bug that occurs on all branches.

**Comment by protonesso** [comment]
dosfstoolsとefibootmgrがインストールされていますか?

**Comment by lap1sid** [comment]
Yes

**Comment by lap1sid** [comment]
It's a very hard problem.

**Comment by mk-linux419** [comment]
インストール完了後も/etc/default/grubのGRUB_DISTRIBUTORがArchのままになっているのが原因だと思います。
何でこうなるのかは不明(calamaresの不具合?)

## 暫定的な対処
### その１
modules/grubcfgのconfのoverwriteを有効にする。

### その２
final-processでArchの部分を置き換える。

その１の場合、/etc/default/grubを作り直すことになるので、その２のほうが良いと思います。

**Comment by Hayao0819** [comment]
https://twitter.com/mk_linux419/status/1248794126029488129
