### ISSUE TITLE
PCManFMのサイドバーにデフォルトのフォルダの一部が存在しない問題。

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#50]
xfce版のthunarでは存在しますがlxde版のPCManFMはサイドバーにドキュメントやみゅーじっくやパブリックやピクチャーなどが存在しない

![VirtualBox_aa32_03_05_2020_15_21_07](https://user-images.githubusercontent.com/50263013/80907406-ead64600-8d51-11ea-983d-72658b2ee8ed.png)

検証iso
https://山d.com/private/alterlinux-lxde-2020.05.03-i686.iso

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
修正できましたが未検証です

**Comment by naoko1010hh** [comment]
修正できていません
![image](https://user-images.githubusercontent.com/50263013/82301755-aa362800-99f3-11ea-9d43-b179f56e51e4.png)

下記の環境でも同様の問題が発生しました

検証iso
https://山d.com/private/alter/beta3-alpha3/alterlinux-lxde-jp-2020.05.18-7cb7529-x86_64.iso

仮想環境
CPU 1コア100%
RAM 4096MB
ホストPC
CPU インテル Core i7-2600（3.4GHz）
RAM 16GB

**Comment by Hayao0819** [comment]
ce8dff551eeb4c2a9a90f55969fd1f37afe9b125 で修正しました
