### ISSUE TITLE
Grubのインストールに失敗する（GPTパーティションにしてしまったため）

### ISSUE THREAD

**Issue by taa829** [FascodeNet/alterlinux#56]
インストール中、99%で突然止まり、下のエラーが出る（一部しか撮れてませんでした...）
![EXDseW7VAAAb5Zd](https://user-images.githubusercontent.com/64528088/80913846-b169fe80-8d82-11ea-87c5-35719058cb11.jpg)

**Comment by Hayao0819** [comment]
機種名やエディション、アーキテクチャなどの詳細をお願いします。

**Comment by watasuke102** [comment]
同じようなエラーが発生しました。（Alter Linux Lxde Beta1、DynaBook t451/46DBS）
本人曰く「ブートローダーのファイル入れるところがシステムファイルと違うストレージだったから、システムファイルと同じにしたら治った」とのことです（お互いよくわかっていません）

![image](https://user-images.githubusercontent.com/36789813/80930081-e9595c00-8deb-11ea-9821-73e01abe77d1.png)

**Comment by Hayao0819** [comment]
おそらくGPTのインストールの方法でMBRを入れてしまったのだと思います
