### ISSUE TITLE
CF-S9でサスペンド復帰時に操作不能になる

### ISSUE THREAD

**Issue by scarlet-Chun-DH** [FascodeNet/alterlinux#59]
使用機種: パナソニック Let’s Note CF-S9
使用エディション: Alter Xfce edition 
以上の環境において、サスペンドからの復帰の際、稀に電源が点いたまま一切操作できなくなり、マジックSysRqも含めて何も為す術なく電源を長押しして強制終了せざるを得ない状況になることがあります。
この時、ファンが異常に回転し、さらに画像に示したタッチパッドの上のランプのうち左端と中央のランプが点滅状態になります。
おそらくは機種依存の問題だと思われますが、何卒よろしくお願いします。
![B54CB48E-227B-4FD5-9779-26172E0D3F80](https://user-images.githubusercontent.com/63408001/80984830-57903400-8e69-11ea-8bf7-adb2e3ad7325.jpeg)

**Comment by Hayao0819** [comment]
[こちらのサイト](http://yang.amp.i.kyoto-u.ac.jp/~yyama/Ubuntu/misc/letsnote-suspend.html)にあるようにLinuxカーネルの問題だと思われます。
上記のサイトのパッチを適用したLinuxカーネルをコンパイルしました。
今日中にはそのカーネルをリポジトリにアップロードしますので適用してみてください。

パッケージ名は`linux-zen-letsnote`です。

また、そのカーネルはAlterLinuxのビルドにも使用できるようになっています。
45c1647563cb2330041cb3709a285106de137a27

**Comment by scarlet-Chun-DH** [comment]
ありがとうございました。

**Comment by scarlet-Chun-DH** [comment]
これをyay経由でダウンロードすればよいということでよろしいでしょうか。
また，pamacからのカーネルアップデートは適用しても大丈夫でしょうか。

**Comment by Hayao0819** [comment]
念の為コマンドラインで行って下さい
以下のコマンドで完全に切り替えることができます

```bash
yay -Syy
yay -S linux-zen-letsnote linux-zen-letsnote-headers
yay -Rsnc linux-zen linux-zen-headers
sudo grub-mkconfig -o /boot/grub/grub.cfg
```

**Comment by scarlet-Chun-DH** [comment]
わかりました。

**Comment by ituki-108** [comment]
改善した模様です
Xeon-e3110 ram-6gb
alterlinux-xfce-2020.05.18-7cb7529-i686.iso

**Comment by Hayao0819** [comment]
@ituki-108 改善を家訓した機種を教えて下さい
