### ISSUE TITLE
AlterLXDEで音量調節がパネルに追加できない

### ISSUE THREAD

**Issue by Tekkamaki4649** [FascodeNet/alterlinux#60]
LXDEパネルの「アイテムを追加、削除」に音量調節と項目があるが追加してもパネルに反映されない、他の物は追加できるので恐らくバグだと思います…
OS Alter日本語版 20.4.26

**Comment by Hayao0819** [comment]
日本語版ですが...
![image](https://user-images.githubusercontent.com/32128205/81176855-bdeb9280-8fe0-11ea-8372-98cc0616d26a.png)
