### ISSUE TITLE
Snapパッケージの対応について

### ISSUE THREAD

**Issue by shamirin** [FascodeNet/alterlinux#62]
### 実行環境
       

- エディション:Alter linux Xfce

-  カーネル:5.6.11-zen1-1-zen

### 問題の内容
snapパッケージをインストールしようと

`$ sudo snap install hello-world`

と入力したら

>error: system does not fully support snapd: cannot mount squashfs image using
       "squashfs": mount: /tmp/sanity-mountpoint-338546357: マウントに失敗しました:
       許可されていない操作です.

と出力されてしまいます。
そのためsnap パッケージをインストールできません。

Line オープンチャットのフォーラムでこの件について質問したところ、
`sudo modprobe loop`
`sudo echo loop >> /etc/modules-load.d/modules.conf`
を実行したら一部のパッケージが実行可能になりました。

### 実行できなかったパッケージ
ただ上記の内容を設定してもvisual studio codeと pycharm-professional が以下のエラーが出力されて起動されません。
  `$ code`
> not root-owned 0:1005

   `$ pycharm-professional`                                           
> not root-owned 0:1005

**Comment by Hayao0819** [comment]
デフォルトでのsnapサポートを追加する予定です。
[ArchWiki - Snap](https://wiki.archlinux.jp/index.php/Snap)

**Comment by Hayao0819** [comment]
5ecada438c8858c9ba9de040b5e413a3468e0aaf と ab06a486b46ab1f032996209e967ac5cd2cda870 でAlterLinuxにsnapの公式サポートが追加されました
これらは次のリリースに反映されます
ただしVScodeやPycharmの問題は未だに原因不明です
