### ISSUE TITLE
インストールに失敗 イメージ "/run/archiso/bootmnt/alter/x86_64/airootfs.sfs" の展開に失敗 エラーコード 10 によりrsyncを失敗。

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#63]
KowerKoint #2306 さんからdiscordにて報告がありましたのでこちらの方にも原文そのまま記述します。

Windows10が入っているノートPCにAlterLinuxを入れようと思いました。
まず、333MBと48GBの容量を持ったパーティションを確保しました。(なぜかWindowsの「ディスクの管理からだと縮小できなかったので「EaseUS」というソフトを使って分割しました)
USBメモリにisoファイル("alterlinux-xfce-jp-2020.04.02-x86_64.iso"と"alterlinux-xfce-jp-2020.04.26-x86_64.iso"の2つを試しました)を焼いて(RufusとEtcherの2つを試しました)BIOSから入りました。(BIOSにはそれっぽいものが"UEFI: UFD 3.0 Silicon-Power 16GPMAP"と"UEFI: UFD 3.0 Silicon-Power 16GPMAP, Partition 1"の2つで、一応両方試しました)
デスクトップにあるインストーラーで、パーティションを割り当てました。48GBのパーティションをマウントポイント"/"にして進もうとすると、「esp フラグを設定したまうとポイント"/boot/efi"のパーティションが必要」といった感じ(正確に控えてない)が表示されました。333MBのほうのパーティションをマウントポイント"/boot/efi"で割り当てました。「esp」という名前のフラグはチェックボックスの列に表示されていませんでしたが、「boot」というフラグにチェックを入れると警告はなくなりました。
ユーザー名やパスワードなどをセットしてインストールを実行しましたが、その途中で「インストールに失敗 イメージ "/run/archiso/bootmnt/alter/x86_64/airootfs.sfs" の展開に失敗 エラーコード 10 によりrsyncを失敗。」というエラーダイアログが出てインストールに失敗します。

正常にインストールするにはどうすればいいでしょうか。
追記：Alterのファイラーで調べたら該当位置にairootfs.sfsは存在はしていました

動作環境
CPU: Intel(R) Core(TM) i7-7700HQ 2.80GHz 2.81 GHz(4コア8スレッド)
メモリ: 16.0 GB
SSD: 256 GB
HDD: 1 TB
インターネット: 有線LAN
GPU: Intel HD Graphics 630
     NVIDIA GeForce MX150
OS: Windows 10 Home (バージョン:1903) 64bit

**Comment by KowerKoint** [comment]
ターミナルから
sudo calamares_polkit -d
と入力してデバッグモードでCalamaresを使い、インストールを進めました。該当のエラーメッセージが出た直前のログは以下の通りです。

07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "machine-id の生成"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "fstab"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "タイムゾーンを Asia/Tokyo に設定"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "キーボードのモデルを pc105 に、レイアウトを jp-に設定"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "localecfg"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "シェルプロセスジョブ"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "luksopenswaphookcfg"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "LUKSキーファイルを設定しています。"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "plymouthcfg"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "initcpiocfg"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "mkinitcpioとinitramfsを作成しています。"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "ターゲットシステムからliveユーザーを消去"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "ユーザー kowerkoint を作成"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "ユーザ kowerkoint のパスワード設定"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "ユーザ root のパスワード設定"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "ホスト名 kowerkoint-mbk686 の設定"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "displaymanager"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "networkcfg"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "hwclock"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "packages"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "services"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "grubcfg"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "bootloader"
07:28:08 [6]: virtual void Calamares::JobThread::run()
Skipping non-emergency job "umount"
07:28:08 [1]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
ERROR:Installation failed:
07:28:08 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
- message: "イメージ \"/run/archiso/bootmnt/alter/x86_64/airootfs.sfs\" の展開に失敗"
07:28:08 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
- details: "エラーコード 10 によりrsyncを失敗。"
07:28:08 [6]: void Calamares::ViewManager::onInstallationFailed(const QString&, const QString&)
Calamares will quit when the dialog closes.
07:28:08 [6]: void CalamaresUtils::callQMLFunction(QQuickItem*, const char*)
QML "onLeave()" is missing.
07:28:08 [6]: void FinishedPage::setUpRestart()
FinishedPage::setUpRestart(), Quit button setup= "never" command= "systemctl -i reboot"

**Comment by KowerKoint** [comment]
新たにespを作っての手動でのパーティション割り当てをやめて自動でのパーティション置換を利用すればエラーが発生することなくインストールすることができました。
"/"と"/boot/efi"といった重複部分を持った割り当てを別々のパーティションに割り当てたのが悪かったのかもしれません。
結局は自分の知識不足だった気がします。ご迷惑をおかけしました。

**Comment by Cipherbit0424** [comment]
https://forum.manjaro.org/t/failed-to-unpack-image-run-miso-bootmnt-manjaro-x86-64-rootfs-sfs/28644
ManjaroLinuxの海外フォーラムでも似たような状況について書かれたものがあったので参考程度に挙げておきます

**Comment by Hayao0819** [comment]
その後Discordで正常にインストールできたとのことですが、その経緯などの詳細を書けませんか？

**Comment by KowerKoint** [comment]
手動でのパーティション割り当てで新たにespフラグ付きのパーティションを作るのをやめ、「パーティションの置換」から割り当てれば正常にインストールできました。
