### ISSUE TITLE
Hyper-VにてXorgが正常に起動しない

### ISSUE THREAD

**Issue by kokkiemouse** [FascodeNet/alterlinux#64]
恐らくXOrgでコケています。
TUIのインストーラーを作成すると良いかもしれません。
![image](https://user-images.githubusercontent.com/39451248/81571551-0f2ec400-93dd-11ea-9881-bd251516e7f0.png)

**Comment by Hayao0819** [comment]
機種やホストOSのバージョンなどの詳細を教えて下さい

**Comment by kokkiemouse** [comment]
Core-i7 2600、DDR3 16GB,Windows 10 20H1、GTX1050Tiです。

**Comment by Hayao0819** [comment]
9b217e5af29c38b42cef54b398f34a6156707aa8 で様々なドライバを追加しました
これでおそらく修正されるはずです

**Comment by Hayao0819** [comment]
2eb66087b6a323fade467f16a9295936a5278801 でGUIの起動方法をLightDmを経由する方法に変更しました
これで修正されると思います

**Comment by kokkiemouse** [comment]
動作しました!
ありがとうございます!
![image](https://user-images.githubusercontent.com/39451248/82807543-ea4d4d00-9ec2-11ea-85a4-e3f6c787367f.png)

**Comment by Hayao0819** [comment]
おおおお！よかったです
