### ISSUE TITLE
Xfce版で壁紙が勝手に変わる

### ISSUE THREAD

**Issue by menndouyukkuri** [FascodeNet/alterlinux#67]
VirtualBoxでAlterLinuxのXfce版を使っている時に、ディスプレイの解像度を何回か変更していると、壁紙が勝手に変わってしまいました。

再現しなかったので、原因は違うかもしれません。

AlterLinux Xfce-JP 20Q1.2.0 Beta 2 (alterlinux-xfce-jp-2020.04.26-x86_64.iso)
Oracle VM VirtualBox 6.1.6

**Comment by menndouyukkuri** [comment]
> VirtualBoxでAlterLinuxのXfce版を使っている時に、ディスプレイの解像度を何回か変更していると、壁紙が勝手に変わってしまいます。
> 
> AlterLinux Xfce-JP 20Q1.2.0 Beta 2 (alterlinux-xfce-jp-2020.04.26-x86_64.iso)
> Oracle VM VirtualBox 6.1.6

**Comment by menndouyukkuri** [comment]
操作ミスしてしまった・・・

**Comment by menndouyukkuri** [comment]
操作ミスしました、申し訳ありません。

**Comment by watasuke102** [comment]
同様の問題を確認しました。sudo pacman -Syu を実行している途中でいきなり変わりました。

- alterlinux-xfce-jp-2020.04.02-x86_64
- VirtualBox 6.0.20
![image](https://user-images.githubusercontent.com/36789813/81876646-24167d80-95be-11ea-9a03-4b1498fd447f.png)

**Comment by Hayao0819** [comment]
パッケージを修正しました
以下のコマンドで解決できると思います。

```bash
yay -Syy
yay -S alterlinux-wallpapers
yay -S xfdesktop
```

**Comment by ituki-108** [comment]
改善した模様です
Xeon-e3110 ram-6gb
alterlinux-xfce-2020.05.18-7cb7529-i686.iso
