### ISSUE TITLE
Plasma版で起動しない

### ISSUE THREAD

**Issue by watasuke102** [FascodeNet/alterlinux#68]
HDDにインストール後起動すると、「Failed to start Light Display Manager.」と表示され、「A start job is running for Hold until boot process finishes up」で止まってしまう

VirtualBox（全グラフィックスコントローラー）で確認

![image](https://user-images.githubusercontent.com/36789813/81807113-7329c780-9558-11ea-8838-90027d95b966.png)

**Comment by Hayao0819** [comment]
おそらく 3d8a09e07e89618c85b85e4c7c1911c271f0f7e5 で修正できました

**Comment by naoko1010hh** [comment]
修正できているようですがこちらでも起動しなかった様子をはっておきます
![image](https://user-images.githubusercontent.com/50263013/81834341-c3fee780-957b-11ea-8be9-8a64eebd0522.png)

検証iso
https://山d.com/private/alter/plasma-test/alterlinux-plasma-2020.05.13-x86_64.iso

仮想環境
CPU 1コア
RAM 2048MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
5c436380344278d165e66fcfb7f292d4d8c46723 で修正しました
