### ISSUE TITLE
Plasma ログインアニメーションをAlter独自のものに変更

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#69]
ライブ起動時にアニメーションがKDEのものになる

https://i.gyazo.com/99b4598a87a708aab6f991db68243335.png
![image](https://user-images.githubusercontent.com/50263013/81808928-72466500-955b-11ea-9318-1c62b40cd8bf.png)

検証iso
https://山d.com/private/alter/plasma-test/alterlinux-plasma-2020.05.13-x86_64.iso

仮想環境
CPU 1コア
RAM 840MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
これはKDEのローディング画面なので仕様です

**Comment by naoko1010hh** [comment]
アニメーションの画像変更方法が判明したので独自のものに変更したいと思います。

**Comment by lap1sid** [comment]
![Screenshot_20200810_142829](https://user-images.githubusercontent.com/48173871/89754197-e4f0bd80-db15-11ea-9817-4c05ec85c306.png)
