### ISSUE TITLE
Dolphinのサイドバーの項目が少ない & インストール後にサイドバーが消える

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#70]
下記に添付してある画像のファイルマネージャーDolphinの左上の部分PlacesにMusic、pictures、public、templates、videosが存在しない

![image](https://user-images.githubusercontent.com/50263013/81810410-db2edc80-955d-11ea-9d8b-d9861e25b907.png)

検証iso
https://山d.com/private/alter/plasma-test/alterlinux-plasma-2020.05.13-x86_64.iso

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
963ce86d7654b5541f7f936ce12ce5c504e137c0 の状態だとインストール後にサイドバーが消えてしまいます

**Comment by lap1sid** [comment]
一応暫定的な修正で処理します

**Comment by lap1sid** [comment]
#255 に引き継ぎ
