### ISSUE TITLE
Plasma版のインストール画面のスライドがXfce版のまま問題

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#71]
Lxdeにも同様の問題が発生していますが、Plasma版にも発生したので報告します。
https://github.com/FascodeNet/alterlinux/issues/52

![image](https://user-images.githubusercontent.com/50263013/81811762-20540e00-9560-11ea-9409-228d62e9baec.png)

検証iso
https://山d.com/private/alter/plasma-test/alterlinux-plasma-2020.05.13-x86_64.iso

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
#52 と重複しています
