### ISSUE TITLE
Plasma版にもPowerLineが欲しい

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#72]
xfce版では実装されているPowerLineが実装されていない問題

![image](https://user-images.githubusercontent.com/50263013/81815112-922e5680-9564-11ea-8f97-22c6156fb488.png)

参考までにxfce版のスクショをはっておきます。
![image](https://fascode.net/projects/linux/alter/img/gallery/Terminal00.png)

検証iso
https://山d.com/private/alter/plasma-test/alterlinux-plasma-2020.05.13-x86_64.iso

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
e8501c7953bdccb23435c2ecedafeb5f24f0f721 で修正しました
