### ISSUE TITLE
Plasma版 htopがインストールされていない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#74]
lxde版やxfce版でインストールされている。CUIシステムモニターhtopコマンドがPlasma版にはインストールされていないので報告します。

![image](https://user-images.githubusercontent.com/50263013/81816441-4aa8ca00-9566-11ea-8688-c14e9e88128e.png)

検証iso
https://山d.com/private/alter/plasma-test/alterlinux-plasma-2020.05.13-x86_64.iso

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
0a2bdc27155fd5e8c17aac544ab2a3a859b9e26d で修正しました

**Comment by Hayao0819** [comment]
0a2bdc27155fd5e8c17aac544ab2a3a859b9e26d で修正しました

**Comment by Hayao0819** [comment]
0a2bdc27155fd5e8c17aac544ab2a3a859b9e26d で修正しました
