### ISSUE TITLE
Inkscapeとgimpを追加してほしい

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#75]
alterlinuxに標準搭載されてほしいソフトウェアを提案します。

gimpとInkscapeを追加してほしいです。

ご検討の程よろしくお願いいたします。

**Comment by Hayao0819** [comment]
イメージファイルのサイズがかなり大きくなってしまう上に一部の人しか利用しないのでいらないかなと考えています

**Comment by Hayao0819** [comment]
Fascode内部投票によりどちらも搭載しないことが決定しました

**Comment by Hayao0819** [comment]
![Screenshot_20200620_183936_com mattermost rnbeta-01](https://user-images.githubusercontent.com/32128205/85198688-a9abec80-b325-11ea-8d97-e111b0b262c4.jpeg)
