### ISSUE TITLE
Plasma版 ライブ環境にて放置するとロックされる。

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#76]
Plasma版 ライブ環境にて放置するとロックされて困ったので報告します。
alterというパスワードを打ってみたら解除できましたが知らない場合実質操作できなくなるのでロックされないように対策をお願いいたします。

![image](https://user-images.githubusercontent.com/50263013/81826950-41722a00-9573-11ea-8e70-34bb905afb8d.png)

検証iso
https://山d.com/private/alter/plasma-test/alterlinux-plasma-2020.05.13-x86_64.iso

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
6dca1646ba5fb5949a4fca368472f8d24a00853c で修正されました
