### ISSUE TITLE
Plasma版にLSDコマンドの装飾（フォント）が設定されてない問題

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#79]
AlterLinuxの特徴の一つであるlsdコマンドの装飾が実装されてない非常に悲しいく解決すべき問題であります

![image](https://user-images.githubusercontent.com/50263013/81919754-34a51300-9613-11ea-88a3-c1e5f255e618.png)

検証iso
https://山d.com/private/alter/plasma-test/alterlinux-plasma-2020.05.13-x86_64.iso

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
東芝ダイナブックPT75TBP-BWA
CPU i7-5500U CPU @ 2.40GHz
RAM 8GB
ROM HDD

**Comment by Hayao0819** [comment]
#72 と同時に既に修正済みです
