### ISSUE TITLE
Lxde版のBETA２にてOSが起動しない Shellループ

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#81]
LINEOpen CHATの方でルミさんからOsが起動しないとの報告がありましたのでgithubにも報告します。

実機環境
Core2 Quad
DDR2の2GB×2　

Lxde版のBETA２似て発生

発生当時のスクリーショット↓
![20200515120817](https://user-images.githubusercontent.com/50263013/82115666-2f74cf00-979f-11ea-8422-81618e626001.jpg)

症状はshellがループするような感じで機動しない

**Comment by Hayao0819** [comment]
CPUやGPUの詳細をお願いします

**Comment by Hayao0819** [comment]
Beta3でGUIを起動する方法が大きく変更されます
これまではXorgで`startx`を直接実行していましたがこれからは`lightdm`サービスを自動ログインで実行します
これによって特殊なハードウェアやドライバの問題ではない限り修正されるはずです。
この変更は 2eb66087b6a323fade467f16a9295936a5278801 でメインラインにマージされました
