### ISSUE TITLE
インストール後インストールメディアを取り出すように促す画面が出ない

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#82]
優先度は低ですが、対応すべきだと思うので報告します。

UbuntuやUbuntuflavour等の有名OSではインストール後再起動するとインストールメディアを外してエンターキーをおしてくださいという表記がでるのですがAlterLinuxではそういう表示が出ない。

**Comment by Hayao0819** [comment]
Calamaresのほうに提案をお願いします。
