### ISSUE TITLE
LXDE版でログイン時にOpenBoxの選択肢がある

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#84]
LXDE版にOpenBoxが混入している問題

![image](https://user-images.githubusercontent.com/50263013/82301607-70652180-99f3-11ea-86d1-cc5b275e6c65.png)

検証iso
https://山d.com/private/alter/beta3-alpha3/alterlinux-lxde-jp-2020.05.18-7cb7529-x86_64.iso

仮想環境
CPU 1コア100%
RAM 4096MB
ホストPC
CPU インテル Core i7-2600（3.4GHz）
RAM 16GB

**Comment by Hayao0819** [comment]
OpenBoxの仕様上仕方のないことなのですが削除したほうが良いでしょうか

**Comment by naoko1010hh** [comment]
削除して問題が起きそうであればそのままでもよいかとですが
できることなら削除すべきかなと思います。

**Comment by Hayao0819** [comment]
他のソフトウェアとの互換性の問題があるのでそのままにしようと思います
Lubuntuなどもそのままなので

**Comment by naoko1010hh** [comment]
了解しました
