### ISSUE TITLE
gUFWが起動できない。

### ISSUE THREAD

**Issue by AQUAjpn** [FascodeNet/alterlinux#87]
gUFWが起動できないです。
ターミナルからUFWを直接有効にはできますが、gUFWは起動画面も表示されません。

//足りないpngファイルがあるみたいですがVBの不調でログ取れないので取れ次第追記します。

**Comment by Hayao0819** [comment]
gUFWは起動ができないのはArchLinuxでも確認しました
おそらく上流の問題になります
最新のAlterLinuxでは`firewalld`と`ufw`を搭載しています
