### ISSUE TITLE
lxde版ライブ起動時にパスワードを求められる

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#89]
![image](https://user-images.githubusercontent.com/50263013/82746454-f3f38980-9dca-11ea-8e1f-c80969fcbd27.png)

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
CPU i7-2600
RAM 15GB
ROM HDD

**Comment by naoko1010hh** [comment]
使用したISO
alterlinux-lxde-2020.05.24-2eb6608-i686.iso

**Comment by naoko1010hh** [comment]
先程上がってきたISOファイルではこの問題は解決していました
使用ISO
https://山d.com/private/alter/beta3-alpha4/lxde-fixed/alterlinux-lxde-2020.05.24-45052bd-x86_64.iso

**Comment by Hayao0819** [comment]
d27c0151b57fc3897d5afff52791004b94de86f6 で修正しました
