### ISSUE TITLE
ライブ環境のインストーラーアイコンがおかしい

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#90]
xfce版は独自のアイコンですがlxde版は普通のアイコン
![image](https://user-images.githubusercontent.com/50263013/82748297-9f0c3f00-9ddb-11ea-9495-0d75166433ce.png)

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
CPU i7-2600
RAM 15GB
ROM HDD

使用したISO
alterlinux-lxde-2020.05.24-2eb6608-i686.iso
alterlinux-xfce-2020.05.24-2eb6608-i686.iso

**Comment by Hayao0819** [comment]
アイコンテーマの違いだと思われます。

**Comment by Hayao0819** [comment]
現在詳細を調査中です

**Comment by Hayao0819** [comment]
9b9856bd315accb28be7dc84958d62267956e5c9 で修正しました
