### ISSUE TITLE
LXDEの ログアウトの画像をAlterLinuxの画像に変更して欲しい

### ISSUE THREAD

**Issue by naoko1010hh** [FascodeNet/alterlinux#92]
![image](https://user-images.githubusercontent.com/50263013/82753544-62533e80-9e01-11ea-8104-a34a6cd56a64.png)

仮想環境
CPU 1コア
RAM 1024MB

ホストPC
CPU i7-2600
RAM 15GB
ROM HDD

使用したISO
https://山d.com/private/alter/beta3-alpha4/lxde-fixed/alterlinux-lxde-2020.05.24-45052bd-x86_64.iso

**Comment by Hayao0819** [comment]
以下のリンクに変更する方法があります
https://askubuntu.com/questions/725674/how-do-i-change-lubuntus-logout-image

**Comment by Hayao0819** [comment]
ArchLinux系は`/usr/share/lxde/images/logout-banner.png`のようです

**Comment by naoko1010hh** [comment]
なるほどそのうちpull送りたいと思います。
