### ISSUE TITLE
Qosmio E10 でイメージファイルが起動しない

### ISSUE THREAD

**Issue by PC-FREEDOM** [FascodeNet/alterlinux#95]
Qosmio E10/2KLDEW にて起動を試みたものの途中でフリーズしてしまいます。
Qosmio E10 の詳細スペック[https://dynabook.com/pc/catalog/qosmio/050117lu/spec.htm](https://dynabook.com/pc/catalog/qosmio/050117lu/spec.htm)

起動の際は DVD からではなく Plop Boot Manager を使い USB メモリから起動させました。

![P1010315](https://user-images.githubusercontent.com/61408321/83328969-bce91080-a2c1-11ea-9b95-d0245b7ecd73.JPG)

GUI なしでも試しましたが、カーソルの点滅だけの画面から進むことができませんでした。
NVIDIA GeForce FX Go5200 を搭載しているのが問題かと思い、NVIDIA 関連のレポートを確認してみましたが解決には至っていません。

**Comment by Hayao0819** [comment]
起動に使用したバージョン（リリース版ならBetaいくつか、自前ビルドなら日付やコミットIDなど）

**Comment by PC-FREEDOM** [comment]
伝え忘れてました。
20Q1.3.0 Beta3 LXDE です。

**Comment by Hayao0819** [comment]
Beta3では正常に起動しないバグがあります
Beta3の翌日に修正版のBeta3.1をリリースしましたのでそちらをお試し下さい
スクリプトのミスで起動しなくなっています

**Comment by PC-FREEDOM** [comment]
わかりました。

**Comment by Hayao0819** [comment]
NVIDIA関連のデバイスで問題が発生する可能性があるのは事実なので、まだ問題が発生するようでしたら教えて下さい

**Comment by PC-FREEDOM** [comment]
わかりました。
確認してみます。
