### ISSUE TITLE
User not known to the underlying authentication moduleと表示され起動できなくなる

### ISSUE THREAD

**Issue by YYTU-Aqua** [FascodeNet/alterlinux#97]
**Describe the bug**
User not known to the underlying authentication moduleと表示されLiveCDが起動できない

**Expected behavior**
./build.sh -b -u Aqua -j xfce

**Desktop (please complete the following information):**
 - OS: AlterLinux
 - Version alterlinux-xfce-jp-2020.06.03-x86_64.iso

**Comment by Hayao0819** [comment]
同様の問題を確認しましたので修正を近々行います。
![image](https://user-images.githubusercontent.com/32128205/84148859-8ddd5680-aa9a-11ea-83c3-276216d3b006.png)

**Comment by YYTU-Aqua** [comment]
ありがとうございます

**Comment by Hayao0819** [comment]
おそらくユーザー名に大文字が入っていたのが原因なので e5ad77738278b3d339af6f145220d8c3e7642101 で大文字を小文字に置き換える処理を追加しました

**Comment by YYTU-Aqua** [comment]
小文字のaにすれば良いんですねありがとうございます

**Comment by YYTU-Aqua** [comment]
ありがとうございます

**Comment by Hayao0819** [comment]
と思ったら修正できていませんでした
もうちょっと検証してみます

**Comment by Hayao0819** [comment]
9fe4b8260ed2aac7a1427675686554a8a59d297a で完全に修正できました
そちらでも確認をお願いします
