### ISSUE TITLE
ファイルマネージャー(GUI)でroot権限が使えるようにしてほしい

### ISSUE THREAD

**Issue by nalamurapepperlinux** [FascodeNet/alterlinux#99]
![スクリーンショット 2020-06-11 19-52-33](https://user-images.githubusercontent.com/66727014/84377173-2b609380-ac1d-11ea-96e4-e6302bbc2659.png)
GUIでファイルマネージャーを起動後、root権限でファイルを開く機能を追加してほしいです。

動作環境
ideapad s12
PepperMint 10とデュアルブート
CPU　intel Atom N270
RAM 1.43GB
ROM 全体・160GB、AlterLinuxのパーミッション・53GB

使用ISO
https://xn--d-8o2b.com/storage/alter/beta/beta3.1/2020.05.26/alterlinux-lxde-2020.05.26-i686.iso

**Comment by Hayao0819** [comment]
10c50c3b667fe61297562e1fe1940fc60a965fa0 でXfce版に追加しました
LXDE版はできるかわかりません...

**Comment by Hayao0819** [comment]
![image](https://user-images.githubusercontent.com/32128205/84382096-1851c180-ac25-11ea-861a-082d4b635b31.png)
